// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class AccelerometerSensorOptions: BridgedDictionary {
    public convenience init(referenceFrame: AccelerometerLocalCoordinateSystem) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.referenceFrame] = referenceFrame.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _referenceFrame = ReadWriteAttribute(jsObject: object, name: Strings.referenceFrame)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var referenceFrame: AccelerometerLocalCoordinateSystem
}
