// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class AudioWorkletNodeOptions: BridgedDictionary {
    public convenience init(numberOfInputs: UInt32, numberOfOutputs: UInt32, outputChannelCount: [UInt32], parameterData: [String: Double], processorOptions: JSObject) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.numberOfInputs] = numberOfInputs.jsValue
        object[Strings.numberOfOutputs] = numberOfOutputs.jsValue
        object[Strings.outputChannelCount] = outputChannelCount.jsValue
        object[Strings.parameterData] = parameterData.jsValue
        object[Strings.processorOptions] = processorOptions.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _numberOfInputs = ReadWriteAttribute(jsObject: object, name: Strings.numberOfInputs)
        _numberOfOutputs = ReadWriteAttribute(jsObject: object, name: Strings.numberOfOutputs)
        _outputChannelCount = ReadWriteAttribute(jsObject: object, name: Strings.outputChannelCount)
        _parameterData = ReadWriteAttribute(jsObject: object, name: Strings.parameterData)
        _processorOptions = ReadWriteAttribute(jsObject: object, name: Strings.processorOptions)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var numberOfInputs: UInt32

    @ReadWriteAttribute
    public var numberOfOutputs: UInt32

    @ReadWriteAttribute
    public var outputChannelCount: [UInt32]

    @ReadWriteAttribute
    public var parameterData: [String: Double]

    @ReadWriteAttribute
    public var processorOptions: JSObject
}
