// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class AudioTrack: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global.AudioTrack.function! }

    private enum Keys {
        static let enabled: JSString = "enabled"
        static let id: JSString = "id"
        static let kind: JSString = "kind"
        static let label: JSString = "label"
        static let language: JSString = "language"
    }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _id = ReadonlyAttribute(jsObject: jsObject, name: Keys.id)
        _kind = ReadonlyAttribute(jsObject: jsObject, name: Keys.kind)
        _label = ReadonlyAttribute(jsObject: jsObject, name: Keys.label)
        _language = ReadonlyAttribute(jsObject: jsObject, name: Keys.language)
        _enabled = ReadWriteAttribute(jsObject: jsObject, name: Keys.enabled)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var id: String

    @ReadonlyAttribute
    public var kind: String

    @ReadonlyAttribute
    public var label: String

    @ReadonlyAttribute
    public var language: String

    @ReadWriteAttribute
    public var enabled: Bool
}
