// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class AudioEncoderInit: BridgedDictionary {
    public convenience init(output: @escaping EncodedAudioChunkOutputCallback, error: @escaping WebCodecsErrorCallback) {
        let object = JSObject.global[Strings.Object].function!.new()
        ClosureAttribute2[Strings.output, in: object] = output
        ClosureAttribute1[Strings.error, in: object] = error
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _output = ClosureAttribute2(jsObject: object, name: Strings.output)
        _error = ClosureAttribute1(jsObject: object, name: Strings.error)
        super.init(unsafelyWrapping: object)
    }

    @ClosureAttribute2
    public var output: EncodedAudioChunkOutputCallback

    @ClosureAttribute1
    public var error: WebCodecsErrorCallback
}
