// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class AudioDecoderConfig: BridgedDictionary {
    public convenience init(codec: String, sampleRate: UInt32, numberOfChannels: UInt32, description: BufferSource) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.codec] = codec.jsValue
        object[Strings.sampleRate] = sampleRate.jsValue
        object[Strings.numberOfChannels] = numberOfChannels.jsValue
        object[Strings.description] = description.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _codec = ReadWriteAttribute(jsObject: object, name: Strings.codec)
        _sampleRate = ReadWriteAttribute(jsObject: object, name: Strings.sampleRate)
        _numberOfChannels = ReadWriteAttribute(jsObject: object, name: Strings.numberOfChannels)
        _description = ReadWriteAttribute(jsObject: object, name: Strings.description)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var codec: String

    @ReadWriteAttribute
    public var sampleRate: UInt32

    @ReadWriteAttribute
    public var numberOfChannels: UInt32

    @ReadWriteAttribute
    public var description: BufferSource
}
