// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class AuthenticatorAttestationResponse: AuthenticatorResponse {
    override public class var constructor: JSFunction { JSObject.global[Strings.AuthenticatorAttestationResponse].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _attestationObject = ReadonlyAttribute(jsObject: jsObject, name: Strings.attestationObject)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadonlyAttribute
    public var attestationObject: ArrayBuffer

    public func getTransports() -> [String] {
        let this = jsObject
        return this[Strings.getTransports].function!(this: this, arguments: []).fromJSValue()!
    }

    public func getAuthenticatorData() -> ArrayBuffer {
        let this = jsObject
        return this[Strings.getAuthenticatorData].function!(this: this, arguments: []).fromJSValue()!
    }

    public func getPublicKey() -> ArrayBuffer? {
        let this = jsObject
        return this[Strings.getPublicKey].function!(this: this, arguments: []).fromJSValue()!
    }

    public func getPublicKeyAlgorithm() -> COSEAlgorithmIdentifier {
        let this = jsObject
        return this[Strings.getPublicKeyAlgorithm].function!(this: this, arguments: []).fromJSValue()!
    }
}
