// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class AuthenticationExtensionsClientOutputs: BridgedDictionary {
    public convenience init(appid: Bool, appidExclude: Bool, uvm: UvmEntries, credProps: CredentialPropertiesOutput, largeBlob: AuthenticationExtensionsLargeBlobOutputs) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.appid] = appid.jsValue()
        object[Strings.appidExclude] = appidExclude.jsValue()
        object[Strings.uvm] = uvm.jsValue()
        object[Strings.credProps] = credProps.jsValue()
        object[Strings.largeBlob] = largeBlob.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _appid = ReadWriteAttribute(jsObject: object, name: Strings.appid)
        _appidExclude = ReadWriteAttribute(jsObject: object, name: Strings.appidExclude)
        _uvm = ReadWriteAttribute(jsObject: object, name: Strings.uvm)
        _credProps = ReadWriteAttribute(jsObject: object, name: Strings.credProps)
        _largeBlob = ReadWriteAttribute(jsObject: object, name: Strings.largeBlob)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var appid: Bool

    @ReadWriteAttribute
    public var appidExclude: Bool

    @ReadWriteAttribute
    public var uvm: UvmEntries

    @ReadWriteAttribute
    public var credProps: CredentialPropertiesOutput

    @ReadWriteAttribute
    public var largeBlob: AuthenticationExtensionsLargeBlobOutputs
}
