// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class BaseComputedKeyframe: BridgedDictionary {
    public convenience init(offset: Double?, computedOffset: Double, easing: String, composite: CompositeOperationOrAuto) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.offset] = offset.jsValue()
        object[Strings.computedOffset] = computedOffset.jsValue()
        object[Strings.easing] = easing.jsValue()
        object[Strings.composite] = composite.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _offset = ReadWriteAttribute(jsObject: object, name: Strings.offset)
        _computedOffset = ReadWriteAttribute(jsObject: object, name: Strings.computedOffset)
        _easing = ReadWriteAttribute(jsObject: object, name: Strings.easing)
        _composite = ReadWriteAttribute(jsObject: object, name: Strings.composite)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var offset: Double?

    @ReadWriteAttribute
    public var computedOffset: Double

    @ReadWriteAttribute
    public var easing: String

    @ReadWriteAttribute
    public var composite: CompositeOperationOrAuto
}
