// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class BluetoothUUID: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.BluetoothUUID].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    public static func getService(name: __UNSUPPORTED_UNION__) -> UUID {
        constructor[Strings.getService]!(name.jsValue()).fromJSValue()!
    }

    public static func getCharacteristic(name: __UNSUPPORTED_UNION__) -> UUID {
        constructor[Strings.getCharacteristic]!(name.jsValue()).fromJSValue()!
    }

    public static func getDescriptor(name: __UNSUPPORTED_UNION__) -> UUID {
        constructor[Strings.getDescriptor]!(name.jsValue()).fromJSValue()!
    }

    public static func canonicalUUID(alias: UInt32) -> UUID {
        constructor[Strings.canonicalUUID]!(alias.jsValue()).fromJSValue()!
    }
}
