// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class BluetoothDevice: EventTarget, BluetoothDeviceEventHandlers, CharacteristicEventHandlers, ServiceEventHandlers {
    override public class var constructor: JSFunction { JSObject.global[Strings.BluetoothDevice].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _id = ReadonlyAttribute(jsObject: jsObject, name: Strings.id)
        _name = ReadonlyAttribute(jsObject: jsObject, name: Strings.name)
        _gatt = ReadonlyAttribute(jsObject: jsObject, name: Strings.gatt)
        _watchingAdvertisements = ReadonlyAttribute(jsObject: jsObject, name: Strings.watchingAdvertisements)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadonlyAttribute
    public var id: String

    @ReadonlyAttribute
    public var name: String?

    @ReadonlyAttribute
    public var gatt: BluetoothRemoteGATTServer?

    public func watchAdvertisements(options: WatchAdvertisementsOptions? = nil) -> JSPromise {
        jsObject[Strings.watchAdvertisements]!(options?.jsValue() ?? .undefined).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func watchAdvertisements(options: WatchAdvertisementsOptions? = nil) async throws {
        let _promise: JSPromise = jsObject[Strings.watchAdvertisements]!(options?.jsValue() ?? .undefined).fromJSValue()!
        _ = try await _promise.get()
    }

    @ReadonlyAttribute
    public var watchingAdvertisements: Bool
}
