// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class BluetoothLEScanFilterInit: BridgedDictionary {
    public convenience init(services: [BluetoothServiceUUID], name: String, namePrefix: String, manufacturerData: [BluetoothManufacturerDataFilterInit], serviceData: [BluetoothServiceDataFilterInit]) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.services] = services.jsValue
        object[Strings.name] = name.jsValue
        object[Strings.namePrefix] = namePrefix.jsValue
        object[Strings.manufacturerData] = manufacturerData.jsValue
        object[Strings.serviceData] = serviceData.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _services = ReadWriteAttribute(jsObject: object, name: Strings.services)
        _name = ReadWriteAttribute(jsObject: object, name: Strings.name)
        _namePrefix = ReadWriteAttribute(jsObject: object, name: Strings.namePrefix)
        _manufacturerData = ReadWriteAttribute(jsObject: object, name: Strings.manufacturerData)
        _serviceData = ReadWriteAttribute(jsObject: object, name: Strings.serviceData)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var services: [BluetoothServiceUUID]

    @ReadWriteAttribute
    public var name: String

    @ReadWriteAttribute
    public var namePrefix: String

    @ReadWriteAttribute
    public var manufacturerData: [BluetoothManufacturerDataFilterInit]

    @ReadWriteAttribute
    public var serviceData: [BluetoothServiceDataFilterInit]
}
