// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol CanvasFilters: JSBridgedClass {}
public extension CanvasFilters {
    var filter: __UNSUPPORTED_UNION__ {
        get { ReadWriteAttribute["filter", in: jsObject] }
        set { ReadWriteAttribute["filter", in: jsObject] = newValue }
    }
}
