// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol CharacteristicEventHandlers: JSBridgedClass {}
public extension CharacteristicEventHandlers {
    var oncharacteristicvaluechanged: EventHandler {
        get { ClosureAttribute.Optional1[Strings.oncharacteristicvaluechanged, in: jsObject] }
        set { ClosureAttribute.Optional1[Strings.oncharacteristicvaluechanged, in: jsObject] = newValue }
    }
}
