// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class Clipboard: EventTarget {
    override public class var constructor: JSFunction { JSObject.global[Strings.Clipboard].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        super.init(unsafelyWrapping: jsObject)
    }

    public func read() -> JSPromise {
        jsObject[Strings.read]!().fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func read() async throws -> ClipboardItems {
        let _promise: JSPromise = jsObject[Strings.read]!().fromJSValue()!
        return try await _promise.get().fromJSValue()!
    }

    public func readText() -> JSPromise {
        jsObject[Strings.readText]!().fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func readText() async throws -> String {
        let _promise: JSPromise = jsObject[Strings.readText]!().fromJSValue()!
        return try await _promise.get().fromJSValue()!
    }

    public func write(data: ClipboardItems) -> JSPromise {
        jsObject[Strings.write]!(data.jsValue()).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func write(data: ClipboardItems) async throws {
        let _promise: JSPromise = jsObject[Strings.write]!(data.jsValue()).fromJSValue()!
        _ = try await _promise.get()
    }

    public func writeText(data: String) -> JSPromise {
        jsObject[Strings.writeText]!(data.jsValue()).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func writeText(data: String) async throws {
        let _promise: JSPromise = jsObject[Strings.writeText]!(data.jsValue()).fromJSValue()!
        _ = try await _promise.get()
    }
}
