// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CollectedClientAdditionalPaymentData: BridgedDictionary {
    public convenience init(rp: String, topOrigin: String, payeeOrigin: String, total: PaymentCurrencyAmount, instrument: PaymentCredentialInstrument) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.rp] = rp.jsValue()
        object[Strings.topOrigin] = topOrigin.jsValue()
        object[Strings.payeeOrigin] = payeeOrigin.jsValue()
        object[Strings.total] = total.jsValue()
        object[Strings.instrument] = instrument.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _rp = ReadWriteAttribute(jsObject: object, name: Strings.rp)
        _topOrigin = ReadWriteAttribute(jsObject: object, name: Strings.topOrigin)
        _payeeOrigin = ReadWriteAttribute(jsObject: object, name: Strings.payeeOrigin)
        _total = ReadWriteAttribute(jsObject: object, name: Strings.total)
        _instrument = ReadWriteAttribute(jsObject: object, name: Strings.instrument)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var rp: String

    @ReadWriteAttribute
    public var topOrigin: String

    @ReadWriteAttribute
    public var payeeOrigin: String

    @ReadWriteAttribute
    public var total: PaymentCurrencyAmount

    @ReadWriteAttribute
    public var instrument: PaymentCredentialInstrument
}
