// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class Comment: CharacterData {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.Comment].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        super.init(unsafelyWrapping: jsObject)
    }

    @inlinable public convenience init(data: String? = nil) {
        self.init(unsafelyWrapping: Self.constructor.new(arguments: [data?.jsValue ?? .undefined]))
    }
}
