// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class ContentIndexEventInit: BridgedDictionary {
    public convenience init(id: String) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.id] = id.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _id = ReadWriteAttribute(jsObject: object, name: Strings.id)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var id: String
}
