// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CookieStoreManager: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.CookieStoreManager].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    public func subscribe(subscriptions: [CookieStoreGetOptions]) -> JSPromise {
        let this = jsObject
        return this[Strings.subscribe].function!(this: this, arguments: [subscriptions.jsValue()]).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func subscribe(subscriptions: [CookieStoreGetOptions]) async throws {
        let this = jsObject
        let _promise: JSPromise = this[Strings.subscribe].function!(this: this, arguments: [subscriptions.jsValue()]).fromJSValue()!
        _ = try await _promise.get()
    }

    public func getSubscriptions() -> JSPromise {
        let this = jsObject
        return this[Strings.getSubscriptions].function!(this: this, arguments: []).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func getSubscriptions() async throws -> [CookieStoreGetOptions] {
        let this = jsObject
        let _promise: JSPromise = this[Strings.getSubscriptions].function!(this: this, arguments: []).fromJSValue()!
        return try await _promise.get().fromJSValue()!
    }

    public func unsubscribe(subscriptions: [CookieStoreGetOptions]) -> JSPromise {
        let this = jsObject
        return this[Strings.unsubscribe].function!(this: this, arguments: [subscriptions.jsValue()]).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func unsubscribe(subscriptions: [CookieStoreGetOptions]) async throws {
        let this = jsObject
        let _promise: JSPromise = this[Strings.unsubscribe].function!(this: this, arguments: [subscriptions.jsValue()]).fromJSValue()!
        _ = try await _promise.get()
    }
}
