// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CredentialsContainer: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.CredentialsContainer].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    public func get(options: CredentialRequestOptions? = nil) -> JSPromise {
        jsObject[Strings.get]!(options?.jsValue() ?? .undefined).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func get(options: CredentialRequestOptions? = nil) async throws -> Credential? {
        let _promise: JSPromise = jsObject[Strings.get]!(options?.jsValue() ?? .undefined).fromJSValue()!
        return try await _promise.get().fromJSValue()!
    }

    public func store(credential: Credential) -> JSPromise {
        jsObject[Strings.store]!(credential.jsValue()).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func store(credential: Credential) async throws -> Credential {
        let _promise: JSPromise = jsObject[Strings.store]!(credential.jsValue()).fromJSValue()!
        return try await _promise.get().fromJSValue()!
    }

    public func create(options: CredentialCreationOptions? = nil) -> JSPromise {
        jsObject[Strings.create]!(options?.jsValue() ?? .undefined).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func create(options: CredentialCreationOptions? = nil) async throws -> Credential? {
        let _promise: JSPromise = jsObject[Strings.create]!(options?.jsValue() ?? .undefined).fromJSValue()!
        return try await _promise.get().fromJSValue()!
    }

    public func preventSilentAccess() -> JSPromise {
        jsObject[Strings.preventSilentAccess]!().fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func preventSilentAccess() async throws {
        let _promise: JSPromise = jsObject[Strings.preventSilentAccess]!().fromJSValue()!
        _ = try await _promise.get()
    }
}
