// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CredentialRequestOptions: BridgedDictionary {
    public convenience init(mediation: CredentialMediationRequirement, signal: AbortSignal, password: Bool, federated: FederatedCredentialRequestOptions, otp: OTPCredentialRequestOptions, publicKey: PublicKeyCredentialRequestOptions) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.mediation] = mediation.jsValue
        object[Strings.signal] = signal.jsValue
        object[Strings.password] = password.jsValue
        object[Strings.federated] = federated.jsValue
        object[Strings.otp] = otp.jsValue
        object[Strings.publicKey] = publicKey.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _mediation = ReadWriteAttribute(jsObject: object, name: Strings.mediation)
        _signal = ReadWriteAttribute(jsObject: object, name: Strings.signal)
        _password = ReadWriteAttribute(jsObject: object, name: Strings.password)
        _federated = ReadWriteAttribute(jsObject: object, name: Strings.federated)
        _otp = ReadWriteAttribute(jsObject: object, name: Strings.otp)
        _publicKey = ReadWriteAttribute(jsObject: object, name: Strings.publicKey)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var mediation: CredentialMediationRequirement

    @ReadWriteAttribute
    public var signal: AbortSignal

    @ReadWriteAttribute
    public var password: Bool

    @ReadWriteAttribute
    public var federated: FederatedCredentialRequestOptions

    @ReadWriteAttribute
    public var otp: OTPCredentialRequestOptions

    @ReadWriteAttribute
    public var publicKey: PublicKeyCredentialRequestOptions
}
