// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CSSHWB: CSSColorValue {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.CSSHWB].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _h = ReadWriteAttribute(jsObject: jsObject, name: Strings.h)
        _w = ReadWriteAttribute(jsObject: jsObject, name: Strings.w)
        _b = ReadWriteAttribute(jsObject: jsObject, name: Strings.b)
        _alpha = ReadWriteAttribute(jsObject: jsObject, name: Strings.alpha)
        super.init(unsafelyWrapping: jsObject)
    }

    @inlinable public convenience init(h: CSSNumericValue, w: CSSNumberish, b: CSSNumberish, alpha: CSSNumberish? = nil) {
        self.init(unsafelyWrapping: Self.constructor.new(arguments: [h.jsValue, w.jsValue, b.jsValue, alpha?.jsValue ?? .undefined]))
    }

    @ReadWriteAttribute
    public var h: CSSNumericValue

    @ReadWriteAttribute
    public var w: CSSNumberish

    @ReadWriteAttribute
    public var b: CSSNumberish

    @ReadWriteAttribute
    public var alpha: CSSNumberish
}
