// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol Any_CSSKeywordValue_or_String: ConvertibleToJSValue {}
extension CSSKeywordValue: Any_CSSKeywordValue_or_String {}
extension String: Any_CSSKeywordValue_or_String {}

public enum CSSKeywordValue_or_String: JSValueCompatible, Any_CSSKeywordValue_or_String {
    case cSSKeywordValue(CSSKeywordValue)
    case string(String)

    public static func construct(from value: JSValue) -> Self? {
        if let cSSKeywordValue: CSSKeywordValue = value.fromJSValue() {
            return .cSSKeywordValue(cSSKeywordValue)
        }
        if let string: String = value.fromJSValue() {
            return .string(string)
        }
        return nil
    }

    public func jsValue() -> JSValue {
        switch self {
        case let .cSSKeywordValue(cSSKeywordValue):
            return cSSKeywordValue.jsValue()
        case let .string(string):
            return string.jsValue()
        }
    }
}
