// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CSSMathClamp: CSSMathValue {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.CSSMathClamp].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _lower = ReadonlyAttribute(jsObject: jsObject, name: Strings.lower)
        _value = ReadonlyAttribute(jsObject: jsObject, name: Strings.value)
        _upper = ReadonlyAttribute(jsObject: jsObject, name: Strings.upper)
        super.init(unsafelyWrapping: jsObject)
    }

    @inlinable public convenience init(lower: CSSNumberish, value: CSSNumberish, upper: CSSNumberish) {
        self.init(unsafelyWrapping: Self.constructor.new(arguments: [lower.jsValue(), value.jsValue(), upper.jsValue()]))
    }

    @ReadonlyAttribute
    public var lower: CSSNumericValue

    @ReadonlyAttribute
    public var value: CSSNumericValue

    @ReadonlyAttribute
    public var upper: CSSNumericValue
}
