// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CSSParserBlock: CSSParserValue {
    override public class var constructor: JSFunction { JSObject.global[Strings.CSSParserBlock].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _name = ReadonlyAttribute(jsObject: jsObject, name: Strings.name)
        _body = ReadonlyAttribute(jsObject: jsObject, name: Strings.body)
        super.init(unsafelyWrapping: jsObject)
    }

    public convenience init(name: String, body: [CSSParserValue]) {
        self.init(unsafelyWrapping: Self.constructor.new(name.jsValue(), body.jsValue()))
    }

    @ReadonlyAttribute
    public var name: String

    @ReadonlyAttribute
    public var body: [CSSParserValue]

    public var description: String {
        jsObject[Strings.toString]!().fromJSValue()!
    }
}
