// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CSSRotate: CSSTransformComponent {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.CSSRotate].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _x = ReadWriteAttribute(jsObject: jsObject, name: Strings.x)
        _y = ReadWriteAttribute(jsObject: jsObject, name: Strings.y)
        _z = ReadWriteAttribute(jsObject: jsObject, name: Strings.z)
        _angle = ReadWriteAttribute(jsObject: jsObject, name: Strings.angle)
        super.init(unsafelyWrapping: jsObject)
    }

    @inlinable public convenience init(angle: CSSNumericValue) {
        self.init(unsafelyWrapping: Self.constructor.new(arguments: [angle.jsValue()]))
    }

    @inlinable public convenience init(x: CSSNumberish, y: CSSNumberish, z: CSSNumberish, angle: CSSNumericValue) {
        self.init(unsafelyWrapping: Self.constructor.new(arguments: [x.jsValue(), y.jsValue(), z.jsValue(), angle.jsValue()]))
    }

    @ReadWriteAttribute
    public var x: CSSNumberish

    @ReadWriteAttribute
    public var y: CSSNumberish

    @ReadWriteAttribute
    public var z: CSSNumberish

    @ReadWriteAttribute
    public var angle: CSSNumericValue
}
