// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CSSStyleDeclaration: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global.CSSStyleDeclaration.function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _cssText = ReadWriteAttribute(jsObject: jsObject, name: Strings.cssText)
        _length = ReadonlyAttribute(jsObject: jsObject, name: Strings.length)
        _parentRule = ReadonlyAttribute(jsObject: jsObject, name: Strings.parentRule)
        _cssFloat = ReadWriteAttribute(jsObject: jsObject, name: Strings.cssFloat)
        self.jsObject = jsObject
    }

    @ReadWriteAttribute
    public var cssText: String

    @ReadonlyAttribute
    public var length: UInt32

    public subscript(key: Int) -> String {
        jsObject[key].fromJSValue()!
    }

    public func getPropertyValue(property: String) -> String {
        jsObject[Strings.getPropertyValue]!(property.jsValue()).fromJSValue()!
    }

    public func getPropertyPriority(property: String) -> String {
        jsObject[Strings.getPropertyPriority]!(property.jsValue()).fromJSValue()!
    }

    public func setProperty(property: String, value: String, priority: String? = nil) {
        _ = jsObject[Strings.setProperty]!(property.jsValue(), value.jsValue(), priority?.jsValue() ?? .undefined)
    }

    public func removeProperty(property: String) -> String {
        jsObject[Strings.removeProperty]!(property.jsValue()).fromJSValue()!
    }

    @ReadonlyAttribute
    public var parentRule: CSSRule?

    @ReadWriteAttribute
    public var cssFloat: String
}
