// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class CSSStyleSheetInit: BridgedDictionary {
    public convenience init(baseURL: String, media: __UNSUPPORTED_UNION__, disabled: Bool) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.baseURL] = baseURL.jsValue()
        object[Strings.media] = media.jsValue()
        object[Strings.disabled] = disabled.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _baseURL = ReadWriteAttribute(jsObject: object, name: Strings.baseURL)
        _media = ReadWriteAttribute(jsObject: object, name: Strings.media)
        _disabled = ReadWriteAttribute(jsObject: object, name: Strings.disabled)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var baseURL: String

    @ReadWriteAttribute
    public var media: __UNSUPPORTED_UNION__

    @ReadWriteAttribute
    public var disabled: Bool
}
