// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol DocumentOrShadowRoot: JSBridgedClass {}
public extension DocumentOrShadowRoot {
    var fullscreenElement: Element? { ReadonlyAttribute[Strings.fullscreenElement, in: jsObject] }

    var pointerLockElement: Element? { ReadonlyAttribute[Strings.pointerLockElement, in: jsObject] }

    func getAnimations() -> [Animation] {
        jsObject[Strings.getAnimations]!().fromJSValue()!
    }

    var activeElement: Element? { ReadonlyAttribute[Strings.activeElement, in: jsObject] }

    var pictureInPictureElement: Element? { ReadonlyAttribute[Strings.pictureInPictureElement, in: jsObject] }

    var styleSheets: StyleSheetList { ReadonlyAttribute[Strings.styleSheets, in: jsObject] }

    var adoptedStyleSheets: [CSSStyleSheet] {
        get { ReadWriteAttribute[Strings.adoptedStyleSheets, in: jsObject] }
        set { ReadWriteAttribute[Strings.adoptedStyleSheets, in: jsObject] = newValue }
    }
}
