// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

private enum Keys {
    static let activeElement: JSString = "activeElement"
    static let adoptedStyleSheets: JSString = "adoptedStyleSheets"
    static let styleSheets: JSString = "styleSheets"
}

public protocol DocumentOrShadowRoot: JSBridgedClass {}
public extension DocumentOrShadowRoot {
    var activeElement: Element? { ReadonlyAttribute[Keys.activeElement, in: jsObject] }

    var styleSheets: StyleSheetList { ReadonlyAttribute[Keys.styleSheets, in: jsObject] }

    var adoptedStyleSheets: [CSSStyleSheet] {
        get { ReadWriteAttribute[Keys.adoptedStyleSheets, in: jsObject] }
        set { ReadWriteAttribute[Keys.adoptedStyleSheets, in: jsObject] = newValue }
    }
}
