// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol Any_DOMMatrix_or_Float32Array_or_Float64Array: ConvertibleToJSValue {}
extension DOMMatrix: Any_DOMMatrix_or_Float32Array_or_Float64Array {}
extension Float32Array: Any_DOMMatrix_or_Float32Array_or_Float64Array {}
extension Float64Array: Any_DOMMatrix_or_Float32Array_or_Float64Array {}

public enum DOMMatrix_or_Float32Array_or_Float64Array: JSValueCompatible, Any_DOMMatrix_or_Float32Array_or_Float64Array {
    case dOMMatrix(DOMMatrix)
    case float32Array(Float32Array)
    case float64Array(Float64Array)

    public static func construct(from value: JSValue) -> Self? {
        if let dOMMatrix: DOMMatrix = value.fromJSValue() {
            return .dOMMatrix(dOMMatrix)
        }
        if let float32Array: Float32Array = value.fromJSValue() {
            return .float32Array(float32Array)
        }
        if let float64Array: Float64Array = value.fromJSValue() {
            return .float64Array(float64Array)
        }
        return nil
    }

    public func jsValue() -> JSValue {
        switch self {
        case let .dOMMatrix(dOMMatrix):
            return dOMMatrix.jsValue()
        case let .float32Array(float32Array):
            return float32Array.jsValue()
        case let .float64Array(float64Array):
            return float64Array.jsValue()
        }
    }
}
