// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class DOMPointReadOnly: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global.DOMPointReadOnly.function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _x = ReadonlyAttribute(jsObject: jsObject, name: "x")
        _y = ReadonlyAttribute(jsObject: jsObject, name: "y")
        _z = ReadonlyAttribute(jsObject: jsObject, name: "z")
        _w = ReadonlyAttribute(jsObject: jsObject, name: "w")
        self.jsObject = jsObject
    }

    public convenience init(x: Double? = nil, y: Double? = nil, z: Double? = nil, w: Double? = nil) {
        self.init(unsafelyWrapping: Self.constructor.new(x?.jsValue() ?? .undefined, y?.jsValue() ?? .undefined, z?.jsValue() ?? .undefined, w?.jsValue() ?? .undefined))
    }

    public static func fromPoint(other: DOMPointInit? = nil) -> Self {
        constructor["fromPoint"]!(other?.jsValue() ?? .undefined).fromJSValue()!
    }

    @ReadonlyAttribute
    public var x: Double

    @ReadonlyAttribute
    public var y: Double

    @ReadonlyAttribute
    public var z: Double

    @ReadonlyAttribute
    public var w: Double

    public func matrixTransform(matrix: DOMMatrixInit? = nil) -> DOMPoint {
        jsObject["matrixTransform"]!(matrix?.jsValue() ?? .undefined).fromJSValue()!
    }

    public func toJSON() -> JSObject {
        jsObject["toJSON"]!().fromJSValue()!
    }
}
