// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class DragEventInit: JSObject {
    public init(dataTransfer: DataTransfer?) {
        let object = JSObject.global.Object.function!.new()
        object["dataTransfer"] = dataTransfer.jsValue()
        _dataTransfer = ReadWriteAttribute(jsObject: object, name: "dataTransfer")
        super.init(cloning: object)
    }

    @ReadWriteAttribute
    public var dataTransfer: DataTransfer?
}
