// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol ElementCSSInlineStyle: JSBridgedClass {}
public extension ElementCSSInlineStyle {
    @inlinable var attributeStyleMap: StylePropertyMap { ReadonlyAttribute[Strings.attributeStyleMap, in: jsObject] }

    @inlinable var style: CSSStyleDeclaration { ReadonlyAttribute[Strings.style, in: jsObject] }
}
