// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol Any_FileSystemHandle_or_WellKnownDirectory: ConvertibleToJSValue {}
extension FileSystemHandle: Any_FileSystemHandle_or_WellKnownDirectory {}
extension WellKnownDirectory: Any_FileSystemHandle_or_WellKnownDirectory {}

public enum FileSystemHandle_or_WellKnownDirectory: JSValueCompatible, Any_FileSystemHandle_or_WellKnownDirectory {
    case fileSystemHandle(FileSystemHandle)
    case wellKnownDirectory(WellKnownDirectory)

    public static func construct(from value: JSValue) -> Self? {
        if let fileSystemHandle: FileSystemHandle = value.fromJSValue() {
            return .fileSystemHandle(fileSystemHandle)
        }
        if let wellKnownDirectory: WellKnownDirectory = value.fromJSValue() {
            return .wellKnownDirectory(wellKnownDirectory)
        }
        return nil
    }

    public func jsValue() -> JSValue {
        switch self {
        case let .fileSystemHandle(fileSystemHandle):
            return fileSystemHandle.jsValue()
        case let .wellKnownDirectory(wellKnownDirectory):
            return wellKnownDirectory.jsValue()
        }
    }
}
