// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class FocusEventInit: JSObject {
    public init(relatedTarget: EventTarget?) {
        let object = JSObject.global.Object.function!.new()
        object["relatedTarget"] = relatedTarget.jsValue()
        _relatedTarget = ReadWriteAttribute(jsObject: object, name: "relatedTarget")
        super.init(cloning: object)
    }

    @ReadWriteAttribute
    public var relatedTarget: EventTarget?
}
