// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class FocusEventInit: BridgedDictionary {
    private enum Keys {
        static let relatedTarget: JSString = "relatedTarget"
    }

    public convenience init(relatedTarget: EventTarget?) {
        let object = JSObject.global.Object.function!.new()
        object[Keys.relatedTarget] = relatedTarget.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _relatedTarget = ReadWriteAttribute(jsObject: object, name: Keys.relatedTarget)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var relatedTarget: EventTarget?
}
