// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class FontMetrics: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.FontMetrics].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _width = ReadonlyAttribute(jsObject: jsObject, name: Strings.width)
        _advances = ReadonlyAttribute(jsObject: jsObject, name: Strings.advances)
        _boundingBoxLeft = ReadonlyAttribute(jsObject: jsObject, name: Strings.boundingBoxLeft)
        _boundingBoxRight = ReadonlyAttribute(jsObject: jsObject, name: Strings.boundingBoxRight)
        _height = ReadonlyAttribute(jsObject: jsObject, name: Strings.height)
        _emHeightAscent = ReadonlyAttribute(jsObject: jsObject, name: Strings.emHeightAscent)
        _emHeightDescent = ReadonlyAttribute(jsObject: jsObject, name: Strings.emHeightDescent)
        _boundingBoxAscent = ReadonlyAttribute(jsObject: jsObject, name: Strings.boundingBoxAscent)
        _boundingBoxDescent = ReadonlyAttribute(jsObject: jsObject, name: Strings.boundingBoxDescent)
        _fontBoundingBoxAscent = ReadonlyAttribute(jsObject: jsObject, name: Strings.fontBoundingBoxAscent)
        _fontBoundingBoxDescent = ReadonlyAttribute(jsObject: jsObject, name: Strings.fontBoundingBoxDescent)
        _dominantBaseline = ReadonlyAttribute(jsObject: jsObject, name: Strings.dominantBaseline)
        _baselines = ReadonlyAttribute(jsObject: jsObject, name: Strings.baselines)
        _fonts = ReadonlyAttribute(jsObject: jsObject, name: Strings.fonts)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var width: Double

    @ReadonlyAttribute
    public var advances: [Double]

    @ReadonlyAttribute
    public var boundingBoxLeft: Double

    @ReadonlyAttribute
    public var boundingBoxRight: Double

    @ReadonlyAttribute
    public var height: Double

    @ReadonlyAttribute
    public var emHeightAscent: Double

    @ReadonlyAttribute
    public var emHeightDescent: Double

    @ReadonlyAttribute
    public var boundingBoxAscent: Double

    @ReadonlyAttribute
    public var boundingBoxDescent: Double

    @ReadonlyAttribute
    public var fontBoundingBoxAscent: Double

    @ReadonlyAttribute
    public var fontBoundingBoxDescent: Double

    @ReadonlyAttribute
    public var dominantBaseline: Baseline

    @ReadonlyAttribute
    public var baselines: [Baseline]

    @ReadonlyAttribute
    public var fonts: [Font]
}
