// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class GPUBindGroup: JSBridgedClass, GPUObjectBase {
    public class var constructor: JSFunction { JSObject.global[Strings.GPUBindGroup].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }
}
