// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class GPUCanvasContext: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.GPUCanvasContext].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _canvas = ReadonlyAttribute(jsObject: jsObject, name: Strings.canvas)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var canvas: __UNSUPPORTED_UNION__

    public func configure(configuration: GPUCanvasConfiguration) {
        _ = jsObject[Strings.configure]!(configuration.jsValue())
    }

    public func unconfigure() {
        _ = jsObject[Strings.unconfigure]!()
    }

    public func getPreferredFormat(adapter: GPUAdapter) -> GPUTextureFormat {
        jsObject[Strings.getPreferredFormat]!(adapter.jsValue()).fromJSValue()!
    }

    public func getCurrentTexture() -> GPUTexture {
        jsObject[Strings.getCurrentTexture]!().fromJSValue()!
    }
}
