// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class GPUImageCopyTexture: BridgedDictionary {
    public convenience init(texture: GPUTexture, mipLevel: GPUIntegerCoordinate, origin: GPUOrigin3D, aspect: GPUTextureAspect) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.texture] = texture.jsValue
        object[Strings.mipLevel] = mipLevel.jsValue
        object[Strings.origin] = origin.jsValue
        object[Strings.aspect] = aspect.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _texture = ReadWriteAttribute(jsObject: object, name: Strings.texture)
        _mipLevel = ReadWriteAttribute(jsObject: object, name: Strings.mipLevel)
        _origin = ReadWriteAttribute(jsObject: object, name: Strings.origin)
        _aspect = ReadWriteAttribute(jsObject: object, name: Strings.aspect)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var texture: GPUTexture

    @ReadWriteAttribute
    public var mipLevel: GPUIntegerCoordinate

    @ReadWriteAttribute
    public var origin: GPUOrigin3D

    @ReadWriteAttribute
    public var aspect: GPUTextureAspect
}
