// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol Any_GPUOrigin2DDict_or_seq_of_GPUIntegerCoordinate: ConvertibleToJSValue {}
extension GPUOrigin2DDict: Any_GPUOrigin2DDict_or_seq_of_GPUIntegerCoordinate {}
extension Array: Any_GPUOrigin2DDict_or_seq_of_GPUIntegerCoordinate where Element == GPUIntegerCoordinate {}

public enum GPUOrigin2DDict_or_seq_of_GPUIntegerCoordinate: JSValueCompatible, Any_GPUOrigin2DDict_or_seq_of_GPUIntegerCoordinate {
    case gPUOrigin2DDict(GPUOrigin2DDict)
    case seq_of_GPUIntegerCoordinate([GPUIntegerCoordinate])

    public static func construct(from value: JSValue) -> Self? {
        if let gPUOrigin2DDict: GPUOrigin2DDict = value.fromJSValue() {
            return .gPUOrigin2DDict(gPUOrigin2DDict)
        }
        if let seq_of_GPUIntegerCoordinate: [GPUIntegerCoordinate] = value.fromJSValue() {
            return .seq_of_GPUIntegerCoordinate(seq_of_GPUIntegerCoordinate)
        }
        return nil
    }

    public func jsValue() -> JSValue {
        switch self {
        case let .gPUOrigin2DDict(gPUOrigin2DDict):
            return gPUOrigin2DDict.jsValue()
        case let .seq_of_GPUIntegerCoordinate(seq_of_GPUIntegerCoordinate):
            return seq_of_GPUIntegerCoordinate.jsValue()
        }
    }
}
