// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol GPUPipelineBase: JSBridgedClass {}
public extension GPUPipelineBase {
    func getBindGroupLayout(index: UInt32) -> GPUBindGroupLayout {
        jsObject[Strings.getBindGroupLayout]!(index.jsValue()).fromJSValue()!
    }
}
