// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class GPURenderPassLayout: BridgedDictionary {
    public convenience init(colorFormats: [GPUTextureFormat?], depthStencilFormat: GPUTextureFormat, sampleCount: GPUSize32) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.colorFormats] = colorFormats.jsValue
        object[Strings.depthStencilFormat] = depthStencilFormat.jsValue
        object[Strings.sampleCount] = sampleCount.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _colorFormats = ReadWriteAttribute(jsObject: object, name: Strings.colorFormats)
        _depthStencilFormat = ReadWriteAttribute(jsObject: object, name: Strings.depthStencilFormat)
        _sampleCount = ReadWriteAttribute(jsObject: object, name: Strings.sampleCount)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var colorFormats: [GPUTextureFormat?]

    @ReadWriteAttribute
    public var depthStencilFormat: GPUTextureFormat

    @ReadWriteAttribute
    public var sampleCount: GPUSize32
}
