// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol GPURenderEncoderBase: JSBridgedClass {}
public extension GPURenderEncoderBase {
    func setPipeline(pipeline: GPURenderPipeline) {
        _ = jsObject[Strings.setPipeline]!(pipeline.jsValue())
    }

    func setIndexBuffer(buffer: GPUBuffer, indexFormat: GPUIndexFormat, offset: GPUSize64? = nil, size: GPUSize64? = nil) {
        _ = jsObject[Strings.setIndexBuffer]!(buffer.jsValue(), indexFormat.jsValue(), offset?.jsValue() ?? .undefined, size?.jsValue() ?? .undefined)
    }

    func setVertexBuffer(slot: GPUIndex32, buffer: GPUBuffer, offset: GPUSize64? = nil, size: GPUSize64? = nil) {
        _ = jsObject[Strings.setVertexBuffer]!(slot.jsValue(), buffer.jsValue(), offset?.jsValue() ?? .undefined, size?.jsValue() ?? .undefined)
    }

    func draw(vertexCount: GPUSize32, instanceCount: GPUSize32? = nil, firstVertex: GPUSize32? = nil, firstInstance: GPUSize32? = nil) {
        _ = jsObject[Strings.draw]!(vertexCount.jsValue(), instanceCount?.jsValue() ?? .undefined, firstVertex?.jsValue() ?? .undefined, firstInstance?.jsValue() ?? .undefined)
    }

    func drawIndexed(indexCount: GPUSize32, instanceCount: GPUSize32? = nil, firstIndex: GPUSize32? = nil, baseVertex: GPUSignedOffset32? = nil, firstInstance: GPUSize32? = nil) {
        _ = jsObject[Strings.drawIndexed]!(indexCount.jsValue(), instanceCount?.jsValue() ?? .undefined, firstIndex?.jsValue() ?? .undefined, baseVertex?.jsValue() ?? .undefined, firstInstance?.jsValue() ?? .undefined)
    }

    func drawIndirect(indirectBuffer: GPUBuffer, indirectOffset: GPUSize64) {
        _ = jsObject[Strings.drawIndirect]!(indirectBuffer.jsValue(), indirectOffset.jsValue())
    }

    func drawIndexedIndirect(indirectBuffer: GPUBuffer, indirectOffset: GPUSize64) {
        _ = jsObject[Strings.drawIndexedIndirect]!(indirectBuffer.jsValue(), indirectOffset.jsValue())
    }
}
