// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class GPURequestAdapterOptions: BridgedDictionary {
    public convenience init(powerPreference: GPUPowerPreference, forceFallbackAdapter: Bool) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.powerPreference] = powerPreference.jsValue
        object[Strings.forceFallbackAdapter] = forceFallbackAdapter.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _powerPreference = ReadWriteAttribute(jsObject: object, name: Strings.powerPreference)
        _forceFallbackAdapter = ReadWriteAttribute(jsObject: object, name: Strings.forceFallbackAdapter)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var powerPreference: GPUPowerPreference

    @ReadWriteAttribute
    public var forceFallbackAdapter: Bool
}
