// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class GPUStorageTextureBindingLayout: BridgedDictionary {
    public convenience init(access: GPUStorageTextureAccess, format: GPUTextureFormat, viewDimension: GPUTextureViewDimension) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.access] = access.jsValue
        object[Strings.format] = format.jsValue
        object[Strings.viewDimension] = viewDimension.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _access = ReadWriteAttribute(jsObject: object, name: Strings.access)
        _format = ReadWriteAttribute(jsObject: object, name: Strings.format)
        _viewDimension = ReadWriteAttribute(jsObject: object, name: Strings.viewDimension)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var access: GPUStorageTextureAccess

    @ReadWriteAttribute
    public var format: GPUTextureFormat

    @ReadWriteAttribute
    public var viewDimension: GPUTextureViewDimension
}
