// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class GPUShaderModuleDescriptor: BridgedDictionary {
    public convenience init(code: String, sourceMap: JSObject, hints: [String: GPUShaderModuleCompilationHint]) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.code] = code.jsValue
        object[Strings.sourceMap] = sourceMap.jsValue
        object[Strings.hints] = hints.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _code = ReadWriteAttribute(jsObject: object, name: Strings.code)
        _sourceMap = ReadWriteAttribute(jsObject: object, name: Strings.sourceMap)
        _hints = ReadWriteAttribute(jsObject: object, name: Strings.hints)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var code: String

    @ReadWriteAttribute
    public var sourceMap: JSObject

    @ReadWriteAttribute
    public var hints: [String: GPUShaderModuleCompilationHint]
}
