// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class GroupEffect: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.GroupEffect].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _children = ReadonlyAttribute(jsObject: jsObject, name: Strings.children)
        _firstChild = ReadonlyAttribute(jsObject: jsObject, name: Strings.firstChild)
        _lastChild = ReadonlyAttribute(jsObject: jsObject, name: Strings.lastChild)
        self.jsObject = jsObject
    }

    public convenience init(children: [AnimationEffect]?, timing: __UNSUPPORTED_UNION__? = nil) {
        self.init(unsafelyWrapping: Self.constructor.new(children.jsValue(), timing?.jsValue() ?? .undefined))
    }

    @ReadonlyAttribute
    public var children: AnimationNodeList

    @ReadonlyAttribute
    public var firstChild: AnimationEffect?

    @ReadonlyAttribute
    public var lastChild: AnimationEffect?

    public func clone() -> Self {
        jsObject[Strings.clone]!().fromJSValue()!
    }

    public func prepend(effects: AnimationEffect...) {
        _ = jsObject[Strings.prepend]!(effects.jsValue())
    }

    public func append(effects: AnimationEffect...) {
        _ = jsObject[Strings.append]!(effects.jsValue())
    }
}
