// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class HkdfParams: BridgedDictionary {
    public convenience init(hash: HashAlgorithmIdentifier, salt: BufferSource, info: BufferSource) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.hash] = hash.jsValue
        object[Strings.salt] = salt.jsValue
        object[Strings.info] = info.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _hash = ReadWriteAttribute(jsObject: object, name: Strings.hash)
        _salt = ReadWriteAttribute(jsObject: object, name: Strings.salt)
        _info = ReadWriteAttribute(jsObject: object, name: Strings.info)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var hash: HashAlgorithmIdentifier

    @ReadWriteAttribute
    public var salt: BufferSource

    @ReadWriteAttribute
    public var info: BufferSource
}
