// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol Any_HTMLOptGroupElement_or_HTMLOptionElement: ConvertibleToJSValue {}
extension HTMLOptGroupElement: Any_HTMLOptGroupElement_or_HTMLOptionElement {}
extension HTMLOptionElement: Any_HTMLOptGroupElement_or_HTMLOptionElement {}

public enum HTMLOptGroupElement_or_HTMLOptionElement: JSValueCompatible, Any_HTMLOptGroupElement_or_HTMLOptionElement {
    case hTMLOptGroupElement(HTMLOptGroupElement)
    case hTMLOptionElement(HTMLOptionElement)

    public static func construct(from value: JSValue) -> Self? {
        if let hTMLOptGroupElement: HTMLOptGroupElement = value.fromJSValue() {
            return .hTMLOptGroupElement(hTMLOptGroupElement)
        }
        if let hTMLOptionElement: HTMLOptionElement = value.fromJSValue() {
            return .hTMLOptionElement(hTMLOptionElement)
        }
        return nil
    }

    public func jsValue() -> JSValue {
        switch self {
        case let .hTMLOptGroupElement(hTMLOptGroupElement):
            return hTMLOptGroupElement.jsValue()
        case let .hTMLOptionElement(hTMLOptionElement):
            return hTMLOptionElement.jsValue()
        }
    }
}
