// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class HTMLModElement: HTMLElement {
    override public class var constructor: JSFunction { JSObject.global.HTMLModElement.function! }

    private enum Keys {
        static let cite: JSString = "cite"
        static let dateTime: JSString = "dateTime"
    }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _cite = ReadWriteAttribute(jsObject: jsObject, name: Keys.cite)
        _dateTime = ReadWriteAttribute(jsObject: jsObject, name: Keys.dateTime)
        super.init(unsafelyWrapping: jsObject)
    }

    public convenience init() {
        self.init(unsafelyWrapping: Self.constructor.new())
    }

    @ReadWriteAttribute
    public var cite: String

    @ReadWriteAttribute
    public var dateTime: String
}
