// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class HTMLProgressElement: HTMLElement {
    override public class var constructor: JSFunction { JSObject.global.HTMLProgressElement.function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _value = ReadWriteAttribute(jsObject: jsObject, name: "value")
        _max = ReadWriteAttribute(jsObject: jsObject, name: "max")
        _position = ReadonlyAttribute(jsObject: jsObject, name: "position")
        _labels = ReadonlyAttribute(jsObject: jsObject, name: "labels")
        super.init(unsafelyWrapping: jsObject)
    }

    public convenience init() {
        self.init(unsafelyWrapping: Self.constructor.new())
    }

    @ReadWriteAttribute
    public var value: Double

    @ReadWriteAttribute
    public var max: Double

    @ReadonlyAttribute
    public var position: Double

    @ReadonlyAttribute
    public var labels: NodeList
}
