// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class HTMLTableCellElement: HTMLElement {
    override public class var constructor: JSFunction { JSObject.global.HTMLTableCellElement.function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _colSpan = ReadWriteAttribute(jsObject: jsObject, name: "colSpan")
        _rowSpan = ReadWriteAttribute(jsObject: jsObject, name: "rowSpan")
        _headers = ReadWriteAttribute(jsObject: jsObject, name: "headers")
        _cellIndex = ReadonlyAttribute(jsObject: jsObject, name: "cellIndex")
        _scope = ReadWriteAttribute(jsObject: jsObject, name: "scope")
        _abbr = ReadWriteAttribute(jsObject: jsObject, name: "abbr")
        _align = ReadWriteAttribute(jsObject: jsObject, name: "align")
        _axis = ReadWriteAttribute(jsObject: jsObject, name: "axis")
        _height = ReadWriteAttribute(jsObject: jsObject, name: "height")
        _width = ReadWriteAttribute(jsObject: jsObject, name: "width")
        _ch = ReadWriteAttribute(jsObject: jsObject, name: "ch")
        _chOff = ReadWriteAttribute(jsObject: jsObject, name: "chOff")
        _noWrap = ReadWriteAttribute(jsObject: jsObject, name: "noWrap")
        _vAlign = ReadWriteAttribute(jsObject: jsObject, name: "vAlign")
        _bgColor = ReadWriteAttribute(jsObject: jsObject, name: "bgColor")
        super.init(unsafelyWrapping: jsObject)
    }

    public convenience init() {
        self.init(unsafelyWrapping: Self.constructor.new())
    }

    @ReadWriteAttribute
    public var colSpan: UInt32

    @ReadWriteAttribute
    public var rowSpan: UInt32

    @ReadWriteAttribute
    public var headers: String

    @ReadonlyAttribute
    public var cellIndex: Int32

    @ReadWriteAttribute
    public var scope: String

    @ReadWriteAttribute
    public var abbr: String

    @ReadWriteAttribute
    public var align: String

    @ReadWriteAttribute
    public var axis: String

    @ReadWriteAttribute
    public var height: String

    @ReadWriteAttribute
    public var width: String

    @ReadWriteAttribute
    public var ch: String

    @ReadWriteAttribute
    public var chOff: String

    @ReadWriteAttribute
    public var noWrap: Bool

    @ReadWriteAttribute
    public var vAlign: String

    @ReadWriteAttribute
    public var bgColor: String
}
