// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol Any_IDBIndex_or_IDBObjectStore: ConvertibleToJSValue {}
extension IDBIndex: Any_IDBIndex_or_IDBObjectStore {}
extension IDBObjectStore: Any_IDBIndex_or_IDBObjectStore {}

public enum IDBIndex_or_IDBObjectStore: JSValueCompatible, Any_IDBIndex_or_IDBObjectStore {
    case iDBIndex(IDBIndex)
    case iDBObjectStore(IDBObjectStore)

    public static func construct(from value: JSValue) -> Self? {
        if let iDBIndex: IDBIndex = value.fromJSValue() {
            return .iDBIndex(iDBIndex)
        }
        if let iDBObjectStore: IDBObjectStore = value.fromJSValue() {
            return .iDBObjectStore(iDBObjectStore)
        }
        return nil
    }

    public func jsValue() -> JSValue {
        switch self {
        case let .iDBIndex(iDBIndex):
            return iDBIndex.jsValue()
        case let .iDBObjectStore(iDBObjectStore):
            return iDBObjectStore.jsValue()
        }
    }
}
