// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class IDBObjectStoreParameters: BridgedDictionary {
    public convenience init(keyPath: String_or_seq_of_String?, autoIncrement: Bool) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.keyPath] = keyPath.jsValue
        object[Strings.autoIncrement] = autoIncrement.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _keyPath = ReadWriteAttribute(jsObject: object, name: Strings.keyPath)
        _autoIncrement = ReadWriteAttribute(jsObject: object, name: Strings.autoIncrement)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var keyPath: String_or_seq_of_String?

    @ReadWriteAttribute
    public var autoIncrement: Bool
}
