// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class IDBOpenDBRequest: IDBRequest {
    override public class var constructor: JSFunction { JSObject.global[Strings.IDBOpenDBRequest].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _onblocked = ClosureAttribute.Optional1(jsObject: jsObject, name: Strings.onblocked)
        _onupgradeneeded = ClosureAttribute.Optional1(jsObject: jsObject, name: Strings.onupgradeneeded)
        super.init(unsafelyWrapping: jsObject)
    }

    @ClosureAttribute.Optional1
    public var onblocked: EventHandler

    @ClosureAttribute.Optional1
    public var onupgradeneeded: EventHandler
}
