// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class ImageEncodeOptions: JSObject {
    public init(type: String, quality: Double) {
        let object = JSObject.global.Object.function!.new()
        object["type"] = type.jsValue()
        object["quality"] = quality.jsValue()
        _type = ReadWriteAttribute(jsObject: object, name: "type")
        _quality = ReadWriteAttribute(jsObject: object, name: "quality")
        super.init(cloning: object)
    }

    @ReadWriteAttribute
    public var type: String

    @ReadWriteAttribute
    public var quality: Double
}
