// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class InputDeviceInfo: MediaDeviceInfo {
    override public class var constructor: JSFunction { JSObject.global[Strings.InputDeviceInfo].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        super.init(unsafelyWrapping: jsObject)
    }

    public func getCapabilities() -> MediaTrackCapabilities {
        jsObject[Strings.getCapabilities]!().fromJSValue()!
    }
}
