// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class ItemDetails: BridgedDictionary {
    public convenience init(itemId: String, title: String, price: PaymentCurrencyAmount, type: ItemType, description: String, iconURLs: [String], subscriptionPeriod: String, freeTrialPeriod: String, introductoryPrice: PaymentCurrencyAmount, introductoryPricePeriod: String, introductoryPriceCycles: UInt64) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.itemId] = itemId.jsValue()
        object[Strings.title] = title.jsValue()
        object[Strings.price] = price.jsValue()
        object[Strings.type] = type.jsValue()
        object[Strings.description] = description.jsValue()
        object[Strings.iconURLs] = iconURLs.jsValue()
        object[Strings.subscriptionPeriod] = subscriptionPeriod.jsValue()
        object[Strings.freeTrialPeriod] = freeTrialPeriod.jsValue()
        object[Strings.introductoryPrice] = introductoryPrice.jsValue()
        object[Strings.introductoryPricePeriod] = introductoryPricePeriod.jsValue()
        object[Strings.introductoryPriceCycles] = introductoryPriceCycles.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _itemId = ReadWriteAttribute(jsObject: object, name: Strings.itemId)
        _title = ReadWriteAttribute(jsObject: object, name: Strings.title)
        _price = ReadWriteAttribute(jsObject: object, name: Strings.price)
        _type = ReadWriteAttribute(jsObject: object, name: Strings.type)
        _description = ReadWriteAttribute(jsObject: object, name: Strings.description)
        _iconURLs = ReadWriteAttribute(jsObject: object, name: Strings.iconURLs)
        _subscriptionPeriod = ReadWriteAttribute(jsObject: object, name: Strings.subscriptionPeriod)
        _freeTrialPeriod = ReadWriteAttribute(jsObject: object, name: Strings.freeTrialPeriod)
        _introductoryPrice = ReadWriteAttribute(jsObject: object, name: Strings.introductoryPrice)
        _introductoryPricePeriod = ReadWriteAttribute(jsObject: object, name: Strings.introductoryPricePeriod)
        _introductoryPriceCycles = ReadWriteAttribute(jsObject: object, name: Strings.introductoryPriceCycles)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var itemId: String

    @ReadWriteAttribute
    public var title: String

    @ReadWriteAttribute
    public var price: PaymentCurrencyAmount

    @ReadWriteAttribute
    public var type: ItemType

    @ReadWriteAttribute
    public var description: String

    @ReadWriteAttribute
    public var iconURLs: [String]

    @ReadWriteAttribute
    public var subscriptionPeriod: String

    @ReadWriteAttribute
    public var freeTrialPeriod: String

    @ReadWriteAttribute
    public var introductoryPrice: PaymentCurrencyAmount

    @ReadWriteAttribute
    public var introductoryPricePeriod: String

    @ReadWriteAttribute
    public var introductoryPriceCycles: UInt64
}
