// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class Lock: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.Lock].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _name = ReadonlyAttribute(jsObject: jsObject, name: Strings.name)
        _mode = ReadonlyAttribute(jsObject: jsObject, name: Strings.mode)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var name: String

    @ReadonlyAttribute
    public var mode: LockMode
}
