// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class MediaCapabilitiesInfo: BridgedDictionary {
    public convenience init(supported: Bool, smooth: Bool, powerEfficient: Bool) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.supported] = supported.jsValue()
        object[Strings.smooth] = smooth.jsValue()
        object[Strings.powerEfficient] = powerEfficient.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _supported = ReadWriteAttribute(jsObject: object, name: Strings.supported)
        _smooth = ReadWriteAttribute(jsObject: object, name: Strings.smooth)
        _powerEfficient = ReadWriteAttribute(jsObject: object, name: Strings.powerEfficient)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var supported: Bool

    @ReadWriteAttribute
    public var smooth: Bool

    @ReadWriteAttribute
    public var powerEfficient: Bool
}
