// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class MediaConfiguration: BridgedDictionary {
    public convenience init(video: VideoConfiguration, audio: AudioConfiguration) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.video] = video.jsValue
        object[Strings.audio] = audio.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _video = ReadWriteAttribute(jsObject: object, name: Strings.video)
        _audio = ReadWriteAttribute(jsObject: object, name: Strings.audio)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var video: VideoConfiguration

    @ReadWriteAttribute
    public var audio: AudioConfiguration
}
