// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class MediaStreamTrack: EventTarget {
    override public class var constructor: JSFunction { JSObject.global[Strings.MediaStreamTrack].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _contentHint = ReadWriteAttribute(jsObject: jsObject, name: Strings.contentHint)
        _isolated = ReadonlyAttribute(jsObject: jsObject, name: Strings.isolated)
        _onisolationchange = ClosureAttribute.Optional1(jsObject: jsObject, name: Strings.onisolationchange)
        _kind = ReadonlyAttribute(jsObject: jsObject, name: Strings.kind)
        _id = ReadonlyAttribute(jsObject: jsObject, name: Strings.id)
        _label = ReadonlyAttribute(jsObject: jsObject, name: Strings.label)
        _enabled = ReadWriteAttribute(jsObject: jsObject, name: Strings.enabled)
        _muted = ReadonlyAttribute(jsObject: jsObject, name: Strings.muted)
        _onmute = ClosureAttribute.Optional1(jsObject: jsObject, name: Strings.onmute)
        _onunmute = ClosureAttribute.Optional1(jsObject: jsObject, name: Strings.onunmute)
        _readyState = ReadonlyAttribute(jsObject: jsObject, name: Strings.readyState)
        _onended = ClosureAttribute.Optional1(jsObject: jsObject, name: Strings.onended)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadWriteAttribute
    public var contentHint: String

    @ReadonlyAttribute
    public var isolated: Bool

    @ClosureAttribute.Optional1
    public var onisolationchange: EventHandler

    @ReadonlyAttribute
    public var kind: String

    @ReadonlyAttribute
    public var id: String

    @ReadonlyAttribute
    public var label: String

    @ReadWriteAttribute
    public var enabled: Bool

    @ReadonlyAttribute
    public var muted: Bool

    @ClosureAttribute.Optional1
    public var onmute: EventHandler

    @ClosureAttribute.Optional1
    public var onunmute: EventHandler

    @ReadonlyAttribute
    public var readyState: MediaStreamTrackState

    @ClosureAttribute.Optional1
    public var onended: EventHandler

    public func clone() -> Self {
        jsObject[Strings.clone]!().fromJSValue()!
    }

    public func stop() {
        _ = jsObject[Strings.stop]!()
    }

    public func getCapabilities() -> MediaTrackCapabilities {
        jsObject[Strings.getCapabilities]!().fromJSValue()!
    }

    public func getConstraints() -> MediaTrackConstraints {
        jsObject[Strings.getConstraints]!().fromJSValue()!
    }

    public func getSettings() -> MediaTrackSettings {
        jsObject[Strings.getSettings]!().fromJSValue()!
    }

    public func applyConstraints(constraints: MediaTrackConstraints? = nil) -> JSPromise {
        jsObject[Strings.applyConstraints]!(constraints?.jsValue() ?? .undefined).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func applyConstraints(constraints: MediaTrackConstraints? = nil) async throws {
        let _promise: JSPromise = jsObject[Strings.applyConstraints]!(constraints?.jsValue() ?? .undefined).fromJSValue()!
        _ = try await _promise.get()
    }
}
