// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class MediaSessionActionDetails: BridgedDictionary {
    public convenience init(action: MediaSessionAction, seekOffset: Double?, seekTime: Double?, fastSeek: Bool?) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.action] = action.jsValue()
        object[Strings.seekOffset] = seekOffset.jsValue()
        object[Strings.seekTime] = seekTime.jsValue()
        object[Strings.fastSeek] = fastSeek.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _action = ReadWriteAttribute(jsObject: object, name: Strings.action)
        _seekOffset = ReadWriteAttribute(jsObject: object, name: Strings.seekOffset)
        _seekTime = ReadWriteAttribute(jsObject: object, name: Strings.seekTime)
        _fastSeek = ReadWriteAttribute(jsObject: object, name: Strings.fastSeek)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var action: MediaSessionAction

    @ReadWriteAttribute
    public var seekOffset: Double?

    @ReadWriteAttribute
    public var seekTime: Double?

    @ReadWriteAttribute
    public var fastSeek: Bool?
}
