// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class MimeType: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global.MimeType.function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _type = ReadonlyAttribute(jsObject: jsObject, name: "type")
        _description = ReadonlyAttribute(jsObject: jsObject, name: "description")
        _suffixes = ReadonlyAttribute(jsObject: jsObject, name: "suffixes")
        _enabledPlugin = ReadonlyAttribute(jsObject: jsObject, name: "enabledPlugin")
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var type: String

    @ReadonlyAttribute
    public var description: String

    @ReadonlyAttribute
    public var suffixes: String

    @ReadonlyAttribute
    public var enabledPlugin: Plugin
}
