// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class ML: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.ML].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    public func createContext(options: MLContextOptions? = nil) -> MLContext {
        jsObject[Strings.createContext]!(options?.jsValue() ?? .undefined).fromJSValue()!
    }

    public func createContext(glContext: WebGLRenderingContext) -> MLContext {
        jsObject[Strings.createContext]!(glContext.jsValue()).fromJSValue()!
    }

    public func createContext(gpuDevice: GPUDevice) -> MLContext {
        jsObject[Strings.createContext]!(gpuDevice.jsValue()).fromJSValue()!
    }
}
