// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class MLBufferResourceView: BridgedDictionary {
    public convenience init(resource: __UNSUPPORTED_UNION__, offset: UInt64, size: UInt64) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.resource] = resource.jsValue()
        object[Strings.offset] = offset.jsValue()
        object[Strings.size] = size.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _resource = ReadWriteAttribute(jsObject: object, name: Strings.resource)
        _offset = ReadWriteAttribute(jsObject: object, name: Strings.offset)
        _size = ReadWriteAttribute(jsObject: object, name: Strings.size)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var resource: __UNSUPPORTED_UNION__

    @ReadWriteAttribute
    public var offset: UInt64

    @ReadWriteAttribute
    public var size: UInt64
}
