// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public enum MLConv2dFilterOperandLayout: JSString, JSValueCompatible {
    case oihw = "oihw"
    case hwio = "hwio"
    case ohwi = "ohwi"
    case ihwo = "ihwo"

    public static func construct(from jsValue: JSValue) -> Self? {
        if let string = jsValue.jsString {
            return Self(rawValue: string)
        }
        return nil
    }

    public init?(string: String) {
        self.init(rawValue: JSString(string))
    }

    public func jsValue() -> JSValue { rawValue.jsValue() }
}
