// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class ModuleExportDescriptor: BridgedDictionary {
    public convenience init(name: String, kind: ImportExportKind) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.name] = name.jsValue()
        object[Strings.kind] = kind.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _name = ReadWriteAttribute(jsObject: object, name: Strings.name)
        _kind = ReadWriteAttribute(jsObject: object, name: Strings.kind)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var name: String

    @ReadWriteAttribute
    public var kind: ImportExportKind
}
