// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol NavigatorCookies: JSBridgedClass {}
public extension NavigatorCookies {
    var cookieEnabled: Bool { ReadonlyAttribute["cookieEnabled", in: jsObject] }
}
