// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol NavigatorStorage: JSBridgedClass {}
public extension NavigatorStorage {
    @inlinable var storage: StorageManager { ReadonlyAttribute[Strings.storage, in: jsObject] }
}
