// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class NetworkInformation: EventTarget, NetworkInformationSaveData {
    override public class var constructor: JSFunction { JSObject.global[Strings.NetworkInformation].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _type = ReadonlyAttribute(jsObject: jsObject, name: Strings.type)
        _effectiveType = ReadonlyAttribute(jsObject: jsObject, name: Strings.effectiveType)
        _downlinkMax = ReadonlyAttribute(jsObject: jsObject, name: Strings.downlinkMax)
        _downlink = ReadonlyAttribute(jsObject: jsObject, name: Strings.downlink)
        _rtt = ReadonlyAttribute(jsObject: jsObject, name: Strings.rtt)
        _onchange = ClosureAttribute.Optional1(jsObject: jsObject, name: Strings.onchange)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadonlyAttribute
    public var type: ConnectionType

    @ReadonlyAttribute
    public var effectiveType: EffectiveConnectionType

    @ReadonlyAttribute
    public var downlinkMax: Megabit

    @ReadonlyAttribute
    public var downlink: Megabit

    @ReadonlyAttribute
    public var rtt: Millisecond

    @ClosureAttribute.Optional1
    public var onchange: EventHandler
}
