// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

private enum Keys {
    static let nextElementSibling: JSString = "nextElementSibling"
    static let previousElementSibling: JSString = "previousElementSibling"
}

public protocol NonDocumentTypeChildNode: JSBridgedClass {}
public extension NonDocumentTypeChildNode {
    var previousElementSibling: Element? { ReadonlyAttribute[Keys.previousElementSibling, in: jsObject] }

    var nextElementSibling: Element? { ReadonlyAttribute[Keys.nextElementSibling, in: jsObject] }
}
