// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol ParentNode: JSBridgedClass {}
public extension ParentNode {
    var children: HTMLCollection { ReadonlyAttribute[Strings.children, in: jsObject] }

    var firstElementChild: Element? { ReadonlyAttribute[Strings.firstElementChild, in: jsObject] }

    var lastElementChild: Element? { ReadonlyAttribute[Strings.lastElementChild, in: jsObject] }

    var childElementCount: UInt32 { ReadonlyAttribute[Strings.childElementCount, in: jsObject] }

    func prepend(nodes: __UNSUPPORTED_UNION__...) {
        _ = jsObject[Strings.prepend]!(nodes.jsValue())
    }

    func append(nodes: __UNSUPPORTED_UNION__...) {
        _ = jsObject[Strings.append]!(nodes.jsValue())
    }

    func replaceChildren(nodes: __UNSUPPORTED_UNION__...) {
        _ = jsObject[Strings.replaceChildren]!(nodes.jsValue())
    }

    func querySelector(selectors: String) -> Element? {
        jsObject[Strings.querySelector]!(selectors.jsValue()).fromJSValue()!
    }

    func querySelectorAll(selectors: String) -> NodeList {
        jsObject[Strings.querySelectorAll]!(selectors.jsValue()).fromJSValue()!
    }
}
