// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class QueuingStrategy: JSObject {
    public init(highWaterMark: Double, size: @escaping QueuingStrategySize) {
        let object = JSObject.global.Object.function!.new()
        object["highWaterMark"] = highWaterMark.jsValue()
        ClosureAttribute.Required1["size", in: object] = size
        _highWaterMark = ReadWriteAttribute(jsObject: object, name: "highWaterMark")
        _size = ClosureAttribute.Required1(jsObject: object, name: "size")
        super.init(cloning: object)
    }

    @ReadWriteAttribute
    public var highWaterMark: Double

    @ClosureAttribute.Required1
    public var size: QueuingStrategySize
}
