// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class ResponseInit: JSObject {
    public init(status: UInt16, statusText: String, headers: HeadersInit) {
        let object = JSObject.global.Object.function!.new()
        object["status"] = status.jsValue()
        object["statusText"] = statusText.jsValue()
        object["headers"] = headers.jsValue()
        _status = ReadWriteAttribute(jsObject: object, name: "status")
        _statusText = ReadWriteAttribute(jsObject: object, name: "statusText")
        _headers = ReadWriteAttribute(jsObject: object, name: "headers")
        super.init(cloning: object)
    }

    @ReadWriteAttribute
    public var status: UInt16

    @ReadWriteAttribute
    public var statusText: String

    @ReadWriteAttribute
    public var headers: HeadersInit
}
