// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class RTCDataChannelInit: BridgedDictionary {
    public convenience init(priority: RTCPriorityType, ordered: Bool, maxPacketLifeTime: UInt16, maxRetransmits: UInt16, protocol: String, negotiated: Bool, id: UInt16) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.priority] = priority.jsValue
        object[Strings.ordered] = ordered.jsValue
        object[Strings.maxPacketLifeTime] = maxPacketLifeTime.jsValue
        object[Strings.maxRetransmits] = maxRetransmits.jsValue
        object[Strings.protocol] = `protocol`.jsValue
        object[Strings.negotiated] = negotiated.jsValue
        object[Strings.id] = id.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _priority = ReadWriteAttribute(jsObject: object, name: Strings.priority)
        _ordered = ReadWriteAttribute(jsObject: object, name: Strings.ordered)
        _maxPacketLifeTime = ReadWriteAttribute(jsObject: object, name: Strings.maxPacketLifeTime)
        _maxRetransmits = ReadWriteAttribute(jsObject: object, name: Strings.maxRetransmits)
        _protocol = ReadWriteAttribute(jsObject: object, name: Strings.protocol)
        _negotiated = ReadWriteAttribute(jsObject: object, name: Strings.negotiated)
        _id = ReadWriteAttribute(jsObject: object, name: Strings.id)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var priority: RTCPriorityType

    @ReadWriteAttribute
    public var ordered: Bool

    @ReadWriteAttribute
    public var maxPacketLifeTime: UInt16

    @ReadWriteAttribute
    public var maxRetransmits: UInt16

    @ReadWriteAttribute
    public var `protocol`: String

    @ReadWriteAttribute
    public var negotiated: Bool

    @ReadWriteAttribute
    public var id: UInt16
}
