// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class RTCIdentityProviderOptions: BridgedDictionary {
    public convenience init(protocol: String, usernameHint: String, peerIdentity: String) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.protocol] = `protocol`.jsValue
        object[Strings.usernameHint] = usernameHint.jsValue
        object[Strings.peerIdentity] = peerIdentity.jsValue
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _protocol = ReadWriteAttribute(jsObject: object, name: Strings.protocol)
        _usernameHint = ReadWriteAttribute(jsObject: object, name: Strings.usernameHint)
        _peerIdentity = ReadWriteAttribute(jsObject: object, name: Strings.peerIdentity)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var `protocol`: String

    @ReadWriteAttribute
    public var usernameHint: String

    @ReadWriteAttribute
    public var peerIdentity: String
}
