// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol Any_RTCRtpScriptTransform_or_SFrameTransform: ConvertibleToJSValue {}
extension RTCRtpScriptTransform: Any_RTCRtpScriptTransform_or_SFrameTransform {}
extension SFrameTransform: Any_RTCRtpScriptTransform_or_SFrameTransform {}

public enum RTCRtpScriptTransform_or_SFrameTransform: JSValueCompatible, Any_RTCRtpScriptTransform_or_SFrameTransform {
    case rTCRtpScriptTransform(RTCRtpScriptTransform)
    case sFrameTransform(SFrameTransform)

    public static func construct(from value: JSValue) -> Self? {
        if let rTCRtpScriptTransform: RTCRtpScriptTransform = value.fromJSValue() {
            return .rTCRtpScriptTransform(rTCRtpScriptTransform)
        }
        if let sFrameTransform: SFrameTransform = value.fromJSValue() {
            return .sFrameTransform(sFrameTransform)
        }
        return nil
    }

    public func jsValue() -> JSValue {
        switch self {
        case let .rTCRtpScriptTransform(rTCRtpScriptTransform):
            return rTCRtpScriptTransform.jsValue()
        case let .sFrameTransform(sFrameTransform):
            return sFrameTransform.jsValue()
        }
    }
}
