// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class RTCRtpScriptTransform: JSBridgedClass {
    @inlinable public class var constructor: JSFunction { JSObject.global[Strings.RTCRtpScriptTransform].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    @inlinable public convenience init(worker: Worker, options: JSValue? = nil, transfer: [JSObject]? = nil) {
        self.init(unsafelyWrapping: Self.constructor.new(arguments: [worker.jsValue, options?.jsValue ?? .undefined, transfer?.jsValue ?? .undefined]))
    }
}
