// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class Sanitizer: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.Sanitizer].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    public convenience init(config: SanitizerConfig? = nil) {
        self.init(unsafelyWrapping: Self.constructor.new(config?.jsValue() ?? .undefined))
    }

    public func sanitize(input: __UNSUPPORTED_UNION__) -> DocumentFragment {
        jsObject[Strings.sanitize]!(input.jsValue()).fromJSValue()!
    }

    public func sanitizeFor(element: String, input: String) -> Element? {
        jsObject[Strings.sanitizeFor]!(element.jsValue(), input.jsValue()).fromJSValue()!
    }

    public func getConfiguration() -> SanitizerConfig {
        jsObject[Strings.getConfiguration]!().fromJSValue()!
    }

    public static func getDefaultConfiguration() -> SanitizerConfig {
        constructor[Strings.getDefaultConfiguration]!().fromJSValue()!
    }
}
