// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class Scheduling: JSBridgedClass {
    @inlinable public class var constructor: JSFunction { JSObject.global[Strings.Scheduling].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    @inlinable public func isInputPending(isInputPendingOptions: IsInputPendingOptions? = nil) -> Bool {
        let this = jsObject
        return this[Strings.isInputPending].function!(this: this, arguments: [isInputPendingOptions?.jsValue() ?? .undefined]).fromJSValue()!
    }
}
