// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol SVGAnimatedPoints: JSBridgedClass {}
public extension SVGAnimatedPoints {
    var points: SVGPointList { ReadonlyAttribute[Strings.points, in: jsObject] }

    var animatedPoints: SVGPointList { ReadonlyAttribute[Strings.animatedPoints, in: jsObject] }
}
