// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SVGComponentTransferFunctionElement: SVGElement {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.SVGComponentTransferFunctionElement].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _type = ReadonlyAttribute(jsObject: jsObject, name: Strings.type)
        _tableValues = ReadonlyAttribute(jsObject: jsObject, name: Strings.tableValues)
        _slope = ReadonlyAttribute(jsObject: jsObject, name: Strings.slope)
        _intercept = ReadonlyAttribute(jsObject: jsObject, name: Strings.intercept)
        _amplitude = ReadonlyAttribute(jsObject: jsObject, name: Strings.amplitude)
        _exponent = ReadonlyAttribute(jsObject: jsObject, name: Strings.exponent)
        _offset = ReadonlyAttribute(jsObject: jsObject, name: Strings.offset)
        super.init(unsafelyWrapping: jsObject)
    }

    public static let SVG_FECOMPONENTTRANSFER_TYPE_UNKNOWN: UInt16 = 0

    public static let SVG_FECOMPONENTTRANSFER_TYPE_IDENTITY: UInt16 = 1

    public static let SVG_FECOMPONENTTRANSFER_TYPE_TABLE: UInt16 = 2

    public static let SVG_FECOMPONENTTRANSFER_TYPE_DISCRETE: UInt16 = 3

    public static let SVG_FECOMPONENTTRANSFER_TYPE_LINEAR: UInt16 = 4

    public static let SVG_FECOMPONENTTRANSFER_TYPE_GAMMA: UInt16 = 5

    @ReadonlyAttribute
    public var type: SVGAnimatedEnumeration

    @ReadonlyAttribute
    public var tableValues: SVGAnimatedNumberList

    @ReadonlyAttribute
    public var slope: SVGAnimatedNumber

    @ReadonlyAttribute
    public var intercept: SVGAnimatedNumber

    @ReadonlyAttribute
    public var amplitude: SVGAnimatedNumber

    @ReadonlyAttribute
    public var exponent: SVGAnimatedNumber

    @ReadonlyAttribute
    public var offset: SVGAnimatedNumber
}
