// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SVGDiscardElement: SVGAnimationElement {
    override public class var constructor: JSFunction { JSObject.global[Strings.SVGDiscardElement].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        super.init(unsafelyWrapping: jsObject)
    }
}
