// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SVGFECompositeElement: SVGElement, SVGFilterPrimitiveStandardAttributes {
    override public class var constructor: JSFunction { JSObject.global[Strings.SVGFECompositeElement].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _in1 = ReadonlyAttribute(jsObject: jsObject, name: Strings.in1)
        _in2 = ReadonlyAttribute(jsObject: jsObject, name: Strings.in2)
        _operator = ReadonlyAttribute(jsObject: jsObject, name: Strings.operator)
        _k1 = ReadonlyAttribute(jsObject: jsObject, name: Strings.k1)
        _k2 = ReadonlyAttribute(jsObject: jsObject, name: Strings.k2)
        _k3 = ReadonlyAttribute(jsObject: jsObject, name: Strings.k3)
        _k4 = ReadonlyAttribute(jsObject: jsObject, name: Strings.k4)
        super.init(unsafelyWrapping: jsObject)
    }

    public static let SVG_FECOMPOSITE_OPERATOR_UNKNOWN: UInt16 = 0

    public static let SVG_FECOMPOSITE_OPERATOR_OVER: UInt16 = 1

    public static let SVG_FECOMPOSITE_OPERATOR_IN: UInt16 = 2

    public static let SVG_FECOMPOSITE_OPERATOR_OUT: UInt16 = 3

    public static let SVG_FECOMPOSITE_OPERATOR_ATOP: UInt16 = 4

    public static let SVG_FECOMPOSITE_OPERATOR_XOR: UInt16 = 5

    public static let SVG_FECOMPOSITE_OPERATOR_ARITHMETIC: UInt16 = 6

    @ReadonlyAttribute
    public var in1: SVGAnimatedString

    @ReadonlyAttribute
    public var in2: SVGAnimatedString

    @ReadonlyAttribute
    public var operator: SVGAnimatedEnumeration

    @ReadonlyAttribute
    public var k1: SVGAnimatedNumber

    @ReadonlyAttribute
    public var k2: SVGAnimatedNumber

    @ReadonlyAttribute
    public var k3: SVGAnimatedNumber

    @ReadonlyAttribute
    public var k4: SVGAnimatedNumber
}
