// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SVGPatternElement: SVGElement, SVGFitToViewBox, SVGURIReference {
    override public class var constructor: JSFunction { JSObject.global[Strings.SVGPatternElement].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _patternUnits = ReadonlyAttribute(jsObject: jsObject, name: Strings.patternUnits)
        _patternContentUnits = ReadonlyAttribute(jsObject: jsObject, name: Strings.patternContentUnits)
        _patternTransform = ReadonlyAttribute(jsObject: jsObject, name: Strings.patternTransform)
        _x = ReadonlyAttribute(jsObject: jsObject, name: Strings.x)
        _y = ReadonlyAttribute(jsObject: jsObject, name: Strings.y)
        _width = ReadonlyAttribute(jsObject: jsObject, name: Strings.width)
        _height = ReadonlyAttribute(jsObject: jsObject, name: Strings.height)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadonlyAttribute
    public var patternUnits: SVGAnimatedEnumeration

    @ReadonlyAttribute
    public var patternContentUnits: SVGAnimatedEnumeration

    @ReadonlyAttribute
    public var patternTransform: SVGAnimatedTransformList

    @ReadonlyAttribute
    public var x: SVGAnimatedLength

    @ReadonlyAttribute
    public var y: SVGAnimatedLength

    @ReadonlyAttribute
    public var width: SVGAnimatedLength

    @ReadonlyAttribute
    public var height: SVGAnimatedLength
}
