// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SVGStyleElement: SVGElement, LinkStyle {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.SVGStyleElement].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _type = ReadWriteAttribute(jsObject: jsObject, name: Strings.type)
        _media = ReadWriteAttribute(jsObject: jsObject, name: Strings.media)
        _title = ReadWriteAttribute(jsObject: jsObject, name: Strings.title)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadWriteAttribute
    public var type: String

    @ReadWriteAttribute
    public var media: String

    @ReadWriteAttribute
    public var title: String
}
