// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SVGStringList: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.SVGStringList].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _length = ReadonlyAttribute(jsObject: jsObject, name: Strings.length)
        _numberOfItems = ReadonlyAttribute(jsObject: jsObject, name: Strings.numberOfItems)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var length: UInt32

    @ReadonlyAttribute
    public var numberOfItems: UInt32

    public func clear() {
        let this = jsObject
        _ = this[Strings.clear].function!(this: this, arguments: [])
    }

    public func initialize(newItem: String) -> String {
        let this = jsObject
        return this[Strings.initialize].function!(this: this, arguments: [newItem.jsValue()]).fromJSValue()!
    }

    public subscript(key: Int) -> String {
        jsObject[key].fromJSValue()!
    }

    public func insertItemBefore(newItem: String, index: UInt32) -> String {
        let this = jsObject
        return this[Strings.insertItemBefore].function!(this: this, arguments: [newItem.jsValue(), index.jsValue()]).fromJSValue()!
    }

    public func replaceItem(newItem: String, index: UInt32) -> String {
        let this = jsObject
        return this[Strings.replaceItem].function!(this: this, arguments: [newItem.jsValue(), index.jsValue()]).fromJSValue()!
    }

    public func removeItem(index: UInt32) -> String {
        let this = jsObject
        return this[Strings.removeItem].function!(this: this, arguments: [index.jsValue()]).fromJSValue()!
    }

    public func appendItem(newItem: String) -> String {
        let this = jsObject
        return this[Strings.appendItem].function!(this: this, arguments: [newItem.jsValue()]).fromJSValue()!
    }

    // XXX: unsupported setter for keys of type UInt32
}
