// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SVGTransformList: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.SVGTransformList].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _length = ReadonlyAttribute(jsObject: jsObject, name: Strings.length)
        _numberOfItems = ReadonlyAttribute(jsObject: jsObject, name: Strings.numberOfItems)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var length: UInt32

    @ReadonlyAttribute
    public var numberOfItems: UInt32

    public func clear() {
        _ = jsObject[Strings.clear]!()
    }

    public func initialize(newItem: SVGTransform) -> SVGTransform {
        jsObject[Strings.initialize]!(newItem.jsValue()).fromJSValue()!
    }

    public subscript(key: Int) -> SVGTransform {
        jsObject[key].fromJSValue()!
    }

    public func insertItemBefore(newItem: SVGTransform, index: UInt32) -> SVGTransform {
        jsObject[Strings.insertItemBefore]!(newItem.jsValue(), index.jsValue()).fromJSValue()!
    }

    public func replaceItem(newItem: SVGTransform, index: UInt32) -> SVGTransform {
        jsObject[Strings.replaceItem]!(newItem.jsValue(), index.jsValue()).fromJSValue()!
    }

    public func removeItem(index: UInt32) -> SVGTransform {
        jsObject[Strings.removeItem]!(index.jsValue()).fromJSValue()!
    }

    public func appendItem(newItem: SVGTransform) -> SVGTransform {
        jsObject[Strings.appendItem]!(newItem.jsValue()).fromJSValue()!
    }

    // XXX: unsupported setter for keys of type UInt32

    public func createSVGTransformFromMatrix(matrix: DOMMatrix2DInit? = nil) -> SVGTransform {
        jsObject[Strings.createSVGTransformFromMatrix]!(matrix?.jsValue() ?? .undefined).fromJSValue()!
    }

    public func consolidate() -> SVGTransform? {
        jsObject[Strings.consolidate]!().fromJSValue()!
    }
}
