// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SVGUnitTypes: JSBridgedClass {
    @inlinable public class var constructor: JSFunction { JSObject.global[Strings.SVGUnitTypes].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    public static let SVG_UNIT_TYPE_UNKNOWN: UInt16 = 0

    public static let SVG_UNIT_TYPE_USERSPACEONUSE: UInt16 = 1

    public static let SVG_UNIT_TYPE_OBJECTBOUNDINGBOX: UInt16 = 2
}
