// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class SyncManager: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.SyncManager].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    public func register(tag: String) -> JSPromise {
        jsObject[Strings.register]!(tag.jsValue()).fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func register(tag: String) async throws {
        let _promise: JSPromise = jsObject[Strings.register]!(tag.jsValue()).fromJSValue()!
        _ = try await _promise.get()
    }

    public func getTags() -> JSPromise {
        jsObject[Strings.getTags]!().fromJSValue()!
    }

    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public func getTags() async throws -> [String] {
        let _promise: JSPromise = jsObject[Strings.getTags]!().fromJSValue()!
        return try await _promise.get().fromJSValue()!
    }
}
