// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class TableDescriptor: BridgedDictionary {
    public convenience init(element: TableKind, initial: UInt32, maximum: UInt32) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.element] = element.jsValue()
        object[Strings.initial] = initial.jsValue()
        object[Strings.maximum] = maximum.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _element = ReadWriteAttribute(jsObject: object, name: Strings.element)
        _initial = ReadWriteAttribute(jsObject: object, name: Strings.initial)
        _maximum = ReadWriteAttribute(jsObject: object, name: Strings.maximum)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var element: TableKind

    @ReadWriteAttribute
    public var initial: UInt32

    @ReadWriteAttribute
    public var maximum: UInt32
}
