// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class TaskPriorityChangeEvent: Event {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.TaskPriorityChangeEvent].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _previousPriority = ReadonlyAttribute(jsObject: jsObject, name: Strings.previousPriority)
        super.init(unsafelyWrapping: jsObject)
    }

    @inlinable public convenience init(type: String, priorityChangeEventInitDict: TaskPriorityChangeEventInit) {
        self.init(unsafelyWrapping: Self.constructor.new(arguments: [type.jsValue(), priorityChangeEventInitDict.jsValue()]))
    }

    @ReadonlyAttribute
    public var previousPriority: TaskPriority
}
