// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class TaskControllerInit: BridgedDictionary {
    public convenience init(priority: TaskPriority) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.priority] = priority.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _priority = ReadWriteAttribute(jsObject: object, name: Strings.priority)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var priority: TaskPriority
}
