// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class TextEncoderEncodeIntoResult: BridgedDictionary {
    public convenience init(read: UInt64, written: UInt64) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.read] = read.jsValue()
        object[Strings.written] = written.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _read = ReadWriteAttribute(jsObject: object, name: Strings.read)
        _written = ReadWriteAttribute(jsObject: object, name: Strings.written)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var read: UInt64

    @ReadWriteAttribute
    public var written: UInt64
}
