// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class TextUpdateEventInit: BridgedDictionary {
    public convenience init(updateRangeStart: UInt32, updateRangeEnd: UInt32, text: String, selectionStart: UInt32, selectionEnd: UInt32, compositionStart: UInt32, compositionEnd: UInt32) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.updateRangeStart] = updateRangeStart.jsValue()
        object[Strings.updateRangeEnd] = updateRangeEnd.jsValue()
        object[Strings.text] = text.jsValue()
        object[Strings.selectionStart] = selectionStart.jsValue()
        object[Strings.selectionEnd] = selectionEnd.jsValue()
        object[Strings.compositionStart] = compositionStart.jsValue()
        object[Strings.compositionEnd] = compositionEnd.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _updateRangeStart = ReadWriteAttribute(jsObject: object, name: Strings.updateRangeStart)
        _updateRangeEnd = ReadWriteAttribute(jsObject: object, name: Strings.updateRangeEnd)
        _text = ReadWriteAttribute(jsObject: object, name: Strings.text)
        _selectionStart = ReadWriteAttribute(jsObject: object, name: Strings.selectionStart)
        _selectionEnd = ReadWriteAttribute(jsObject: object, name: Strings.selectionEnd)
        _compositionStart = ReadWriteAttribute(jsObject: object, name: Strings.compositionStart)
        _compositionEnd = ReadWriteAttribute(jsObject: object, name: Strings.compositionEnd)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var updateRangeStart: UInt32

    @ReadWriteAttribute
    public var updateRangeEnd: UInt32

    @ReadWriteAttribute
    public var text: String

    @ReadWriteAttribute
    public var selectionStart: UInt32

    @ReadWriteAttribute
    public var selectionEnd: UInt32

    @ReadWriteAttribute
    public var compositionStart: UInt32

    @ReadWriteAttribute
    public var compositionEnd: UInt32
}
