// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class TimeRanges: JSBridgedClass {
    @inlinable public class var constructor: JSFunction { JSObject.global[Strings.TimeRanges].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _length = ReadonlyAttribute(jsObject: jsObject, name: Strings.length)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var length: UInt32

    @inlinable public func start(index: UInt32) -> Double {
        let this = jsObject
        return this[Strings.start].function!(this: this, arguments: [index.jsValue]).fromJSValue()!
    }

    @inlinable public func end(index: UInt32) -> Double {
        let this = jsObject
        return this[Strings.end].function!(this: this, arguments: [index.jsValue]).fromJSValue()!
    }
}
