// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class TransformStream: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.TransformStream].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _readable = ReadonlyAttribute(jsObject: jsObject, name: Strings.readable)
        _writable = ReadonlyAttribute(jsObject: jsObject, name: Strings.writable)
        self.jsObject = jsObject
    }

    public convenience init(transformer: JSObject? = nil, writableStrategy: QueuingStrategy? = nil, readableStrategy: QueuingStrategy? = nil) {
        self.init(unsafelyWrapping: Self.constructor.new(transformer?.jsValue() ?? .undefined, writableStrategy?.jsValue() ?? .undefined, readableStrategy?.jsValue() ?? .undefined))
    }

    @ReadonlyAttribute
    public var readable: ReadableStream

    @ReadonlyAttribute
    public var writable: WritableStream
}
