// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class URL: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global.URL.function! }

    private enum Keys {
        static let createObjectURL: JSString = "createObjectURL"
        static let revokeObjectURL: JSString = "revokeObjectURL"
    }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        self.jsObject = jsObject
    }

    public static func createObjectURL(obj: __UNSUPPORTED_UNION__) -> String {
        constructor[Keys.createObjectURL]!(obj.jsValue()).fromJSValue()!
    }

    public static func revokeObjectURL(url: String) {
        constructor[Keys.revokeObjectURL]!(url.jsValue()).fromJSValue()!
    }
}
