// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public enum ValueType: JSString, JSValueCompatible {
    case i32 = "i32"
    case i64 = "i64"
    case f32 = "f32"
    case f64 = "f64"
    case v128 = "v128"
    case externref = "externref"
    case anyfunc = "anyfunc"

    @inlinable public static func construct(from jsValue: JSValue) -> Self? {
        if let string = jsValue.jsString {
            return Self(rawValue: string)
        }
        return nil
    }

    @inlinable public init?(string: String) {
        self.init(rawValue: JSString(string))
    }

    @inlinable public var jsValue: JSValue { rawValue.jsValue }
}
