// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public protocol Any_VibratePattern: ConvertibleToJSValue {}
extension UInt32: Any_VibratePattern {}
extension Array: Any_VibratePattern where Element == UInt32 {}

public enum VibratePattern: JSValueCompatible, Any_VibratePattern {
    case uInt32(UInt32)
    case seq_of_UInt32([UInt32])

    public static func construct(from value: JSValue) -> Self? {
        if let uInt32: UInt32 = value.fromJSValue() {
            return .uInt32(uInt32)
        }
        if let seq_of_UInt32: [UInt32] = value.fromJSValue() {
            return .seq_of_UInt32(seq_of_UInt32)
        }
        return nil
    }

    public var jsValue: JSValue {
        switch self {
        case let .uInt32(uInt32):
            return uInt32.jsValue
        case let .seq_of_UInt32(seq_of_UInt32):
            return seq_of_UInt32.jsValue
        }
    }
}
