// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class VirtualKeyboard: EventTarget {
    override public class var constructor: JSFunction { JSObject.global[Strings.VirtualKeyboard].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _boundingRect = ReadonlyAttribute(jsObject: jsObject, name: Strings.boundingRect)
        _overlaysContent = ReadWriteAttribute(jsObject: jsObject, name: Strings.overlaysContent)
        _ongeometrychange = ClosureAttribute.Optional1(jsObject: jsObject, name: Strings.ongeometrychange)
        super.init(unsafelyWrapping: jsObject)
    }

    public func show() {
        _ = jsObject[Strings.show]!()
    }

    public func hide() {
        _ = jsObject[Strings.hide]!()
    }

    @ReadonlyAttribute
    public var boundingRect: DOMRect

    @ReadWriteAttribute
    public var overlaysContent: Bool

    @ClosureAttribute.Optional1
    public var ongeometrychange: EventHandler
}
