// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class WebGLActiveInfo: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.WebGLActiveInfo].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _size = ReadonlyAttribute(jsObject: jsObject, name: Strings.size)
        _type = ReadonlyAttribute(jsObject: jsObject, name: Strings.type)
        _name = ReadonlyAttribute(jsObject: jsObject, name: Strings.name)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var size: GLint

    @ReadonlyAttribute
    public var type: GLenum

    @ReadonlyAttribute
    public var name: String
}
