// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class WindowPostMessageOptions: JSObject {
    public init(targetOrigin: String) {
        let object = JSObject.global.Object.function!.new()
        object["targetOrigin"] = targetOrigin.jsValue()
        _targetOrigin = ReadWriteAttribute(jsObject: object, name: "targetOrigin")
        super.init(cloning: object)
    }

    @ReadWriteAttribute
    public var targetOrigin: String
}
