// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

private enum Keys {
    static let localStorage: JSString = "localStorage"
}

public protocol WindowLocalStorage: JSBridgedClass {}
public extension WindowLocalStorage {
    var localStorage: Storage { ReadonlyAttribute[Keys.localStorage, in: jsObject] }
}
