// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class WindowPostMessageOptions: BridgedDictionary {
    private enum Keys {
        static let targetOrigin: JSString = "targetOrigin"
    }

    public convenience init(targetOrigin: String) {
        let object = JSObject.global.Object.function!.new()
        object[Keys.targetOrigin] = targetOrigin.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _targetOrigin = ReadWriteAttribute(jsObject: object, name: Keys.targetOrigin)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var targetOrigin: String
}
