// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XMLHttpRequestEventTarget: EventTarget {
    override public class var constructor: JSFunction { JSObject.global.XMLHttpRequestEventTarget.function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _onloadstart = ClosureAttribute.Optional1(jsObject: jsObject, name: "onloadstart")
        _onprogress = ClosureAttribute.Optional1(jsObject: jsObject, name: "onprogress")
        _onabort = ClosureAttribute.Optional1(jsObject: jsObject, name: "onabort")
        _onerror = ClosureAttribute.Optional1(jsObject: jsObject, name: "onerror")
        _onload = ClosureAttribute.Optional1(jsObject: jsObject, name: "onload")
        _ontimeout = ClosureAttribute.Optional1(jsObject: jsObject, name: "ontimeout")
        _onloadend = ClosureAttribute.Optional1(jsObject: jsObject, name: "onloadend")
        super.init(unsafelyWrapping: jsObject)
    }

    @ClosureAttribute.Optional1
    public var onloadstart: EventHandler

    @ClosureAttribute.Optional1
    public var onprogress: EventHandler

    @ClosureAttribute.Optional1
    public var onabort: EventHandler

    @ClosureAttribute.Optional1
    public var onerror: EventHandler

    @ClosureAttribute.Optional1
    public var onload: EventHandler

    @ClosureAttribute.Optional1
    public var ontimeout: EventHandler

    @ClosureAttribute.Optional1
    public var onloadend: EventHandler
}
