// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XRBoundedReferenceSpace: XRReferenceSpace {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.XRBoundedReferenceSpace].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _boundsGeometry = ReadonlyAttribute(jsObject: jsObject, name: Strings.boundsGeometry)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadonlyAttribute
    public var boundsGeometry: [DOMPointReadOnly]
}
