// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XRCubeLayer: XRCompositionLayer {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.XRCubeLayer].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _space = ReadWriteAttribute(jsObject: jsObject, name: Strings.space)
        _orientation = ReadWriteAttribute(jsObject: jsObject, name: Strings.orientation)
        _onredraw = ClosureAttribute1Optional(jsObject: jsObject, name: Strings.onredraw)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadWriteAttribute
    public var space: XRSpace

    @ReadWriteAttribute
    public var orientation: DOMPointReadOnly

    @ClosureAttribute1Optional
    public var onredraw: EventHandler
}
