// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XRDepthInformation: JSBridgedClass {
    public class var constructor: JSFunction { JSObject.global[Strings.XRDepthInformation].function! }

    public let jsObject: JSObject

    public required init(unsafelyWrapping jsObject: JSObject) {
        _width = ReadonlyAttribute(jsObject: jsObject, name: Strings.width)
        _height = ReadonlyAttribute(jsObject: jsObject, name: Strings.height)
        _normDepthBufferFromNormView = ReadonlyAttribute(jsObject: jsObject, name: Strings.normDepthBufferFromNormView)
        _rawValueToMeters = ReadonlyAttribute(jsObject: jsObject, name: Strings.rawValueToMeters)
        self.jsObject = jsObject
    }

    @ReadonlyAttribute
    public var width: UInt32

    @ReadonlyAttribute
    public var height: UInt32

    @ReadonlyAttribute
    public var normDepthBufferFromNormView: XRRigidTransform

    @ReadonlyAttribute
    public var rawValueToMeters: Float
}
