// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XREquirectLayer: XRCompositionLayer {
    override public class var constructor: JSFunction { JSObject.global[Strings.XREquirectLayer].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _space = ReadWriteAttribute(jsObject: jsObject, name: Strings.space)
        _transform = ReadWriteAttribute(jsObject: jsObject, name: Strings.transform)
        _radius = ReadWriteAttribute(jsObject: jsObject, name: Strings.radius)
        _centralHorizontalAngle = ReadWriteAttribute(jsObject: jsObject, name: Strings.centralHorizontalAngle)
        _upperVerticalAngle = ReadWriteAttribute(jsObject: jsObject, name: Strings.upperVerticalAngle)
        _lowerVerticalAngle = ReadWriteAttribute(jsObject: jsObject, name: Strings.lowerVerticalAngle)
        _onredraw = ClosureAttribute1Optional(jsObject: jsObject, name: Strings.onredraw)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadWriteAttribute
    public var space: XRSpace

    @ReadWriteAttribute
    public var transform: XRRigidTransform

    @ReadWriteAttribute
    public var radius: Float

    @ReadWriteAttribute
    public var centralHorizontalAngle: Float

    @ReadWriteAttribute
    public var upperVerticalAngle: Float

    @ReadWriteAttribute
    public var lowerVerticalAngle: Float

    @ClosureAttribute1Optional
    public var onredraw: EventHandler
}
