// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XRHitTestOptionsInit: BridgedDictionary {
    public convenience init(space: XRSpace, entityTypes: [XRHitTestTrackableType], offsetRay: XRRay) {
        let object = JSObject.global[Strings.Object].function!.new()
        object[Strings.space] = space.jsValue()
        object[Strings.entityTypes] = entityTypes.jsValue()
        object[Strings.offsetRay] = offsetRay.jsValue()
        self.init(unsafelyWrapping: object)
    }

    public required init(unsafelyWrapping object: JSObject) {
        _space = ReadWriteAttribute(jsObject: object, name: Strings.space)
        _entityTypes = ReadWriteAttribute(jsObject: object, name: Strings.entityTypes)
        _offsetRay = ReadWriteAttribute(jsObject: object, name: Strings.offsetRay)
        super.init(unsafelyWrapping: object)
    }

    @ReadWriteAttribute
    public var space: XRSpace

    @ReadWriteAttribute
    public var entityTypes: [XRHitTestTrackableType]

    @ReadWriteAttribute
    public var offsetRay: XRRay
}
