// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XRJointPose: XRPose {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.XRJointPose].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _radius = ReadonlyAttribute(jsObject: jsObject, name: Strings.radius)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadonlyAttribute
    public var radius: Float
}
