// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XRSessionEvent: Event {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.XRSessionEvent].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _session = ReadonlyAttribute(jsObject: jsObject, name: Strings.session)
        super.init(unsafelyWrapping: jsObject)
    }

    @inlinable public convenience init(type: String, eventInitDict: XRSessionEventInit) {
        self.init(unsafelyWrapping: Self.constructor.new(arguments: [type.jsValue(), eventInitDict.jsValue()]))
    }

    @ReadonlyAttribute
    public var session: XRSession
}
