// This file was auto-generated by WebIDLToSwift. DO NOT EDIT!

import JavaScriptEventLoop
import JavaScriptKit

public class XRWebGLSubImage: XRSubImage {
    @inlinable override public class var constructor: JSFunction { JSObject.global[Strings.XRWebGLSubImage].function! }

    public required init(unsafelyWrapping jsObject: JSObject) {
        _colorTexture = ReadonlyAttribute(jsObject: jsObject, name: Strings.colorTexture)
        _depthStencilTexture = ReadonlyAttribute(jsObject: jsObject, name: Strings.depthStencilTexture)
        _imageIndex = ReadonlyAttribute(jsObject: jsObject, name: Strings.imageIndex)
        _textureWidth = ReadonlyAttribute(jsObject: jsObject, name: Strings.textureWidth)
        _textureHeight = ReadonlyAttribute(jsObject: jsObject, name: Strings.textureHeight)
        super.init(unsafelyWrapping: jsObject)
    }

    @ReadonlyAttribute
    public var colorTexture: WebGLTexture

    @ReadonlyAttribute
    public var depthStencilTexture: WebGLTexture?

    @ReadonlyAttribute
    public var imageIndex: UInt32?

    @ReadonlyAttribute
    public var textureWidth: UInt32

    @ReadonlyAttribute
    public var textureHeight: UInt32
}
